#!/usr/bin/env python3
"""Reference implementation of the canonicalisation fixed by ADR-0020.

This is contract tooling, not platform runtime code. It exists so that the test
vectors in ``schemas/hashing/vectors.json`` are generated by something readable
rather than asserted by hand, and so CI can check that the vectors and the rules
still agree.

RFC 8785 (JSON Canonicalization Scheme), restricted by ADR-0020 §2 to documents
containing no floating point and no null. The restriction removes the only part
of RFC 8785 that is genuinely difficult to implement identically in two
languages: number formatting delegated to ECMAScript ``Number::toString``.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

MAX_SAFE_INTEGER = 2**53 - 1

# RFC 8785 inherits ECMAScript JSON.stringify escaping: the two structural
# characters, plus the five short forms, plus \u00xx for anything else below
# 0x20. Nothing at or above 0x20 is ever escaped -- notably DEL (0x7f) and every
# non-ASCII character are emitted literally as UTF-8.
_SHORT_ESCAPES = {
    0x08: "\\b",
    0x09: "\\t",
    0x0A: "\\n",
    0x0C: "\\f",
    0x0D: "\\r",
    0x22: '\\"',
    0x5C: "\\\\",
}


def _escape(text: str) -> str:
    out = ['"']
    for char in text:
        code = ord(char)
        short = _SHORT_ESCAPES.get(code)
        if short is not None:
            out.append(short)
        elif code < 0x20:
            out.append(f"\\u{code:04x}")
        else:
            out.append(char)
    out.append('"')
    return "".join(out)


def _utf16_sort_key(key: str) -> bytes:
    """Order keys by UTF-16 code unit, as RFC 8785 requires.

    Python's default string ordering is by code point, which agrees with UTF-16
    order for the Basic Multilingual Plane and disagrees above it: a
    supplementary-plane character (U+10000 and above) is encoded as a surrogate
    pair whose first unit lies in U+D800..U+DBFF, so it sorts *below* the
    unpaired BMP characters U+E000..U+FFFF rather than above them. Sorting on
    the UTF-16 big-endian encoding reproduces the required order directly.
    """
    return key.encode("utf-16-be")


def canonicalize(value: Any) -> str:
    """Return the canonical JSON text for a value.

    Raises ValueError on anything ADR-0020 excludes from a hashed document, so a
    violation surfaces where it is introduced rather than as a hash that two
    languages compute differently.
    """
    if value is None:
        raise ValueError("null is not a member of a hashed document (ADR-0020 §3)")
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, int):
        if abs(value) > MAX_SAFE_INTEGER:
            raise ValueError(f"integer {value} exceeds ±(2^53 − 1) (ADR-0020 §2)")
        return str(value)
    if isinstance(value, float):
        raise ValueError("hashed documents contain no floating point (ADR-0020 §2)")
    if isinstance(value, str):
        return _escape(value)
    if isinstance(value, list):
        return "[" + ",".join(canonicalize(item) for item in value) + "]"
    if isinstance(value, dict):
        keys = sorted(value, key=_utf16_sort_key)
        if len(set(keys)) != len(keys):
            raise ValueError("duplicate object keys are invalid input (ADR-0020 §1)")
        parts = (f"{_escape(k)}:{canonicalize(value[k])}" for k in keys)
        return "{" + ",".join(parts) + "}"
    raise ValueError(f"unsupported type in a hashed document: {type(value).__name__}")


def strip_excluded(value: Any, excluded: frozenset[str]) -> Any:
    """Remove properties annotated ``x-hashExclude`` (ADR-0020 §4).

    Applied recursively: a nested object carrying a self-referencing field is
    treated the same way as the root, since the reason is identical.
    """
    if isinstance(value, dict):
        return {
            k: strip_excluded(v, excluded) for k, v in value.items() if k not in excluded
        }
    if isinstance(value, list):
        return [strip_excluded(item, excluded) for item in value]
    return value


def content_hash(document: Any, excluded: frozenset[str] = frozenset()) -> str:
    canonical = canonicalize(strip_excluded(document, excluded))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def main() -> int:
    """Read a JSON document on stdin, print its canonical form and digest."""
    import sys

    document = json.load(sys.stdin)
    canonical = canonicalize(document)
    print(canonical)
    print(hashlib.sha256(canonical.encode("utf-8")).hexdigest())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
