#!/usr/bin/env python3
"""Generate Java and Python contract models from the canonical JSON Schemas.

ADR-0024: ``schemas/**/*.schema.json`` is the single source of truth, one
generator emits both languages, and the output is committed so CI can regenerate
and diff.

Two rules shape everything here.

**Generated models carry no behaviour** (ADR-0024 §4). They are data carriers
with fields, equality and explicit conversion to and from JSON-compatible
structures. Validation is performed against the JSON Schema by a validator, not
by hand-maintained checks embedded in generated classes, so a generated type can
hold an invalid document. That is intentional: parsing and validation are
separate steps.

**Absent means absent** (ADR-0020 §3). Optional fields with no value are omitted
on serialisation and are never written as ``null``, in either language.

Usage:
    python3 .github/scripts/codegen.py            # write
    python3 .github/scripts/codegen.py --check    # fail if output would change
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SCHEMAS = ROOT / "schemas"
JAVA_ROOT = ROOT / "contracts" / "java"
PYTHON_ROOT = ROOT / "contracts" / "python"
JAVA_PACKAGE = "io.aiplatform.contracts"

# A flat Java package and a single Python module are deliberate. Schema titles
# are globally unique by ADR-0019, so nothing collides, and a flat namespace
# means the generator never has to compute an import graph across cross-file
# $refs -- which is where a generator of this kind usually acquires its bugs.
JAVA_SRC = JAVA_ROOT / "src" / "main" / "java" / Path(*JAVA_PACKAGE.split("."))
PYTHON_PKG = PYTHON_ROOT / "aiplatform_contracts"

BANNER_LINES = [
    "Generated by .github/scripts/codegen.py from {source}.",
    "",
    "DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI",
    "fails if the committed output differs (ADR-0024 §3).",
]


# --------------------------------------------------------------------------
# Schema loading and $ref resolution
# --------------------------------------------------------------------------


def load_schemas() -> dict[Path, dict]:
    documents: dict[Path, dict] = {}
    for path in sorted(SCHEMAS.rglob("*.schema.json")):
        documents[path.resolve()] = json.loads(path.read_text(encoding="utf-8"))
    return documents


def resolve_ref(ref: str, base: Path, documents: dict[Path, dict]) -> tuple[Path, list[str], dict]:
    """Resolve a $ref to (owning file, JSON pointer segments, node)."""
    file_part, _, pointer = ref.partition("#")
    target = (base.parent / file_part).resolve() if file_part else base
    node: Any = documents[target]
    segments = [seg for seg in pointer.split("/") if seg]
    for segment in segments:
        node = node[segment]
    return target, segments, node


# --------------------------------------------------------------------------
# Type model
# --------------------------------------------------------------------------


@dataclass
class Field:
    name: str
    type: "TypeRef"
    required: bool
    description: str | None


@dataclass
class TypeRef:
    """How a value is expressed in each target language."""

    java: str
    python: str
    kind: str = "scalar"  # scalar | record | enum | list | map | freeform
    inner: "TypeRef | None" = None
    """Element type of a list or value type of a map.

    Carried explicitly rather than recovered by parsing the rendered type name:
    string matching on ``Map<String, dict[str, Any]>`` is how a generator starts
    emitting calls to methods that do not exist on the element type.
    """


@dataclass
class RecordType:
    name: str
    source: str
    description: str | None
    fields: list[Field] = field(default_factory=list)


@dataclass
class EnumType:
    name: str
    source: str
    description: str | None
    values: list[str] = field(default_factory=list)


class Generator:
    def __init__(self, documents: dict[Path, dict]) -> None:
        self.documents = documents
        self.records: dict[str, RecordType] = {}
        self.enums: dict[str, EnumType] = {}
        self._ref_names: dict[tuple[Path, str], str] = {}
        self._in_progress: set[tuple[Path, str]] = set()

    # -- naming ----------------------------------------------------------

    @staticmethod
    def pascal(text: str) -> str:
        parts = re.split(r"[^0-9a-zA-Z]+", text)
        return "".join(p[:1].upper() + p[1:] for p in parts if p)

    def register_name(self, base: str) -> str:
        name = self.pascal(base)
        if name in self.records or name in self.enums:
            # Two schemas producing the same type name is a vocabulary defect
            # (ADR-0019), not something to paper over with a numeric suffix.
            raise SystemExit(f"codegen: duplicate generated type name {name!r}")
        return name

    # -- traversal -------------------------------------------------------

    def run(self) -> None:
        for path in sorted(self.documents):
            document = self.documents[path]
            source = path.relative_to(ROOT).as_posix()
            title = document.get("title", "")
            if path.name == "common.schema.json":
                prefix = ""
            else:
                prefix = self.pascal(title)
            for def_name, def_node in sorted(document.get("$defs", {}).items()):
                self.type_for(def_node, path, f"{prefix}{self.pascal(def_name)}", source)
            if document.get("type") == "object" and "properties" in document:
                self.type_for(document, path, self.pascal(title), source)

    def type_for(self, node: dict, base: Path, suggested: str, source: str) -> TypeRef:
        """Return the TypeRef for a schema node, generating named types as needed."""
        if "$ref" in node:
            target, segments, resolved = resolve_ref(node["$ref"], base, self.documents)
            key = (target, "/".join(segments))
            if key in self._ref_names:
                name = self._ref_names[key]
                if name in self.enums:
                    return TypeRef(name, name, "enum")
                if name in self.records:
                    return TypeRef(name, name, "record")
            target_doc = self.documents[target]
            if segments and segments[0] == "$defs":
                prefix = "" if target.name == "common.schema.json" else self.pascal(
                    target_doc.get("title", "")
                )
                suggested = f"{prefix}{self.pascal(segments[-1])}"
            else:
                suggested = self.pascal(target_doc.get("title", suggested))
            if key in self._in_progress:
                # A self-referential schema -- Condition's expression tree is the
                # real case. Only a named composite can recur, so the name is
                # enough to close the cycle.
                return TypeRef(suggested, suggested, "record")
            self._in_progress.add(key)
            try:
                ref = self.type_for(
                    resolved, target, suggested, target.relative_to(ROOT).as_posix()
                )
            finally:
                self._in_progress.discard(key)
            if ref.kind in ("record", "enum"):
                self._ref_names[key] = ref.java
            return ref

        if "enum" in node and node.get("type", "string") == "string":
            return self.make_enum(node, suggested, source)

        if "oneOf" in node:
            return self.make_union(node, base, suggested, source)

        node_type = node.get("type")

        if "const" in node:
            value = node["const"]
            if isinstance(value, str):
                return TypeRef("String", "str")
            if isinstance(value, bool):
                return TypeRef("Boolean", "bool")

        if node_type == "array":
            item = node.get("items", {})
            inner = self.type_for(item, base, f"{suggested}Item", source)
            return TypeRef(
                f"List<{self.boxed(inner.java)}>", f"list[{inner.python}]", "list", inner
            )

        if node_type == "string":
            return TypeRef("String", "str")
        if node_type == "integer":
            return TypeRef("long", "int")
        if node_type == "boolean":
            return TypeRef("boolean", "bool")
        if node_type == "number":
            # ADR-0020 §2 excludes floating point from hashed documents only.
            return TypeRef("double", "float")

        if node_type == "object" or "properties" in node:
            additional = node.get("additionalProperties")
            if "properties" not in node and isinstance(additional, dict):
                inner = self.type_for(additional, base, f"{suggested}Value", source)
                return TypeRef(
                    f"Map<String, {self.boxed(inner.java)}>",
                    f"dict[str, {inner.python}]",
                    "map",
                    inner,
                )
            if "properties" not in node and "patternProperties" in node:
                return TypeRef(
                    "Map<String, String>", "dict[str, str]", "map", TypeRef("String", "str")
                )
            if "properties" not in node:
                # A free-form object: an embedded JSON Schema, a validated tool
                # input, a claimed agent output. Deliberately untyped -- its shape
                # is declared elsewhere and is not known at generation time.
                return TypeRef("Map<String, Object>", "dict[str, Any]", "freeform")
            if additional is True:
                # Properties are declared, but so is everything else: Tool.inputSchema
                # constrains one key of an embedded JSON Schema and leaves the rest
                # open. A record would silently discard every undeclared key on a
                # round trip, which is worse than being untyped.
                return TypeRef("Map<String, Object>", "dict[str, Any]", "freeform")
            return self.make_record(node, base, suggested, source)

        return TypeRef("Object", "Any", "freeform")

    def make_enum(self, node: dict, suggested: str, source: str) -> TypeRef:
        values = list(node["enum"])
        for name, existing in self.enums.items():
            if existing.values == values and name == suggested:
                return TypeRef(name, name, "enum")
        if suggested in self.enums:
            if self.enums[suggested].values == values:
                return TypeRef(suggested, suggested, "enum")
            raise SystemExit(f"codegen: conflicting enum definitions for {suggested!r}")
        self.enums[suggested] = EnumType(
            name=suggested,
            source=source,
            description=node.get("description"),
            values=values,
        )
        return TypeRef(suggested, suggested, "enum")

    def make_record(self, node: dict, base: Path, suggested: str, source: str) -> TypeRef:
        if suggested in self.records:
            return TypeRef(suggested, suggested, "record")
        record = RecordType(name=suggested, source=source, description=node.get("description"))
        # Registered before its fields are built so a self-referential schema
        # terminates rather than recursing forever.
        self.records[suggested] = record
        required = set(node.get("required", []))
        for prop_name, prop_node in node.get("properties", {}).items():
            prop_type = self.type_for(
                prop_node, base, f"{suggested}{self.pascal(prop_name)}", source
            )
            record.fields.append(
                Field(
                    name=prop_name,
                    type=prop_type,
                    required=prop_name in required,
                    description=prop_node.get("description"),
                )
            )
        # Required first so Java constructor order is stable and Python defaults
        # are legal; within each group, schema order is preserved.
        record.fields.sort(key=lambda f: not f.required)
        return TypeRef(suggested, suggested, "record")

    def make_union(self, node: dict, base: Path, suggested: str, source: str) -> TypeRef:
        """Flatten a oneOf into one record whose branch fields are all optional.

        ADR-0024 §4a. A sealed hierarchy would be more expressive, but only for
        the subset of unions discriminated by a const, and the schema set mixes
        those with unions distinguished only by which fields are present. One
        representation for both keeps the generated API uniform, and since
        validation is by JSON Schema the branch rule is still enforced -- just
        not by the type.
        """
        branches: list[tuple[dict, Path]] = []
        for branch in node["oneOf"]:
            branch_base = base
            while "$ref" in branch:
                branch_base, _, branch = resolve_ref(branch["$ref"], branch_base, self.documents)
            branches.append((branch, branch_base))

        if not all("properties" in branch for branch, _ in branches):
            # A union mixing a scalar with an object -- ModelRequest.toolChoice is
            # "AUTO" or {"name": ...}. No single generated type describes both, and
            # inventing a wrapper would put a shape in the code that the wire format
            # does not have.
            return TypeRef("Object", "Any", "freeform")

        record = RecordType(
            name=suggested,
            source=source,
            description=(node.get("description") or "")
            + " Union of mutually exclusive branches; exactly one branch's required"
            " fields are present in a valid document, which the JSON Schema enforces"
            " and this type does not.",
        )
        self.records[suggested] = record
        # A property may appear in several branches with different schemas -- the
        # discriminator is exactly that case, since each branch constrains it to
        # its own value. Collect every occurrence and merge, rather than letting
        # the first branch win: taking the first is how a discriminator ends up
        # missing the values of every branch after the first.
        occurrences: dict[str, list[tuple[dict, Path]]] = {}
        order: list[str] = []
        for branch, branch_base in branches:
            for prop_name, prop_node in branch.get("properties", {}).items():
                if prop_name not in occurrences:
                    occurrences[prop_name] = []
                    order.append(prop_name)
                occurrences[prop_name].append((prop_node, branch_base))
        for prop_name in order:
            entries = occurrences[prop_name]
            prop_type = self.merge_property(
                entries, f"{suggested}{self.pascal(prop_name)}", source
            )
            record.fields.append(
                Field(
                    name=prop_name,
                    type=prop_type,
                    required=False,
                    description=entries[0][0].get("description"),
                )
            )
        return TypeRef(suggested, suggested, "record")

    def merge_property(
        self, entries: list[tuple[dict, Path]], suggested: str, source: str
    ) -> TypeRef:
        """Reconcile one property's schema across the branches of a union."""
        resolved: list[tuple[dict, Path]] = []
        for prop_node, prop_base in entries:
            current, current_base = prop_node, prop_base
            while "$ref" in current:
                current_base, _, current = resolve_ref(
                    current["$ref"], current_base, self.documents
                )
            resolved.append((current, current_base))

        # Discriminators: each branch pins the property to a const or a small
        # enum, and the union of those values is the real domain.
        values: list[str] = []
        all_string_choices = True
        for current, _ in resolved:
            if "enum" in current and current.get("type", "string") == "string":
                values += [v for v in current["enum"] if v not in values]
            elif isinstance(current.get("const"), str):
                if current["const"] not in values:
                    values.append(current["const"])
            else:
                all_string_choices = False
                break
        if all_string_choices and values:
            return self.make_enum(
                {
                    "enum": values,
                    "description": (
                        "Discriminates the branches of the union. The members are the "
                        "union of the values each branch permits."
                    ),
                },
                suggested,
                source,
            )

        canonical = json.dumps(resolved[0][0], sort_keys=True)
        if all(json.dumps(current, sort_keys=True) == canonical for current, _ in resolved):
            return self.type_for(entries[0][0], entries[0][1], suggested, source)

        # Genuinely different shapes under one name. Untyped is the honest
        # outcome: any single generated type here would misdescribe some branch.
        return TypeRef("Object", "Any", "freeform")

    # -- helpers ---------------------------------------------------------

    @staticmethod
    def boxed(java_type: str) -> str:
        return {"long": "Long", "boolean": "Boolean", "double": "Double"}.get(
            java_type, java_type
        )

    @staticmethod
    def java_field_type(f: Field) -> str:
        return f.type.java if f.required else Generator.boxed(f.type.java)


# --------------------------------------------------------------------------
# Emitters
# --------------------------------------------------------------------------


def banner(source: str, comment: str = " * ") -> list[str]:
    return [line.format(source=source) for line in BANNER_LINES]


def wrap(text: str, width: int = 92) -> list[str]:
    words, lines, current = text.split(), [], ""
    for word in words:
        if current and len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines


def java_doc(description: str | None, source: str, indent: str = "") -> list[str]:
    out = [f"{indent}/**"]
    if description:
        for line in wrap(description):
            out.append(f"{indent} * {line}")
        out.append(f"{indent} *")
    for line in banner(source):
        out.append(f"{indent} * {line}".rstrip())
    out.append(f"{indent} */")
    return out


def emit_java_enum(enum: EnumType) -> str:
    lines = [f"package {JAVA_PACKAGE};", ""]
    lines += java_doc(enum.description, enum.source)
    lines.append(f"public enum {enum.name} {{")
    for index, value in enumerate(enum.values):
        constant = re.sub(r"[^0-9A-Za-z]+", "_", value).upper()
        if constant[:1].isdigit():
            constant = "_" + constant
        comma = "," if index < len(enum.values) - 1 else ";"
        lines.append(f'    {constant}("{value}"){comma}')
    lines += [
        "",
        "    private final String wire;",
        "",
        f"    {enum.name}(String wire) {{",
        "        this.wire = wire;",
        "    }",
        "",
        "    /** The value as it appears in JSON, which is not always the constant name. */",
        "    public String wire() {",
        "        return wire;",
        "    }",
        "",
        f"    public static {enum.name} fromWire(String value) {{",
        f"        for ({enum.name} candidate : values()) {{",
        "            if (candidate.wire.equals(value)) {",
        "                return candidate;",
        "            }",
        "        }",
        "        throw new IllegalArgumentException(",
        f'                "unknown {enum.name} value: " + value);',
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def java_from_expr(f: Field, source: str) -> str:
    """Java expression converting a Map value to the field's type."""
    t = f.type
    if t.kind == "enum":
        return f"{t.java}.fromWire((String) {source})"
    if t.kind == "record":
        return f"{t.java}.fromMap(asMap({source}))"
    if t.kind == "list":
        inner = t.inner
        if inner is None or inner.kind not in ("record", "enum"):
            return f"asList({source})"
        if inner.kind == "enum":
            return f"asList({source}).stream().map(e -> {inner.java}.fromWire((String) e)).toList()"
        return f"asList({source}).stream().map(e -> {inner.java}.fromMap(asMap(e))).toList()"
    if t.kind == "map":
        inner = t.inner
        if inner is None or inner.kind not in ("record", "enum"):
            return f"asMap({source})"
        if inner.kind == "enum":
            return (
                f"asMap({source}).entrySet().stream().collect(java.util.stream.Collectors"
                f".toMap(java.util.Map.Entry::getKey, e -> {inner.java}.fromWire((String) e.getValue())))"
            )
        return (
            f"asMap({source}).entrySet().stream().collect(java.util.stream.Collectors"
            f".toMap(java.util.Map.Entry::getKey, e -> {inner.java}.fromMap(asMap(e.getValue()))))"
        )
    if t.java == "long":
        return f"((Number) {source}).longValue()"
    if t.java == "boolean":
        return f"(Boolean) {source}"
    if t.java == "double":
        return f"((Number) {source}).doubleValue()"
    return f"({Generator.boxed(t.java)}) {source}"


def java_to_expr(f: Field) -> str:
    t = f.type
    name = java_name(f.name)
    if t.kind == "enum":
        return f"{name}.wire()"
    if t.kind == "record":
        return f"{name}.toMap()"
    if t.kind == "list":
        inner = t.inner
        if inner is None or inner.kind not in ("record", "enum"):
            return name
        method = "wire" if inner.kind == "enum" else "toMap"
        return f"{name}.stream().map({inner.java}::{method}).toList()"
    if t.kind == "map":
        inner = t.inner
        if inner is None or inner.kind not in ("record", "enum"):
            return name
        method = "wire" if inner.kind == "enum" else "toMap"
        return (
            f"{name}.entrySet().stream().collect(java.util.stream.Collectors.toMap("
            f"java.util.Map.Entry::getKey, e -> e.getValue().{method}()))"
        )
    return name


# Java keywords that a JSON field name could plausibly collide with. Condition's
# "const" branch is the case that actually occurs; the rest are cheap insurance.
JAVA_RESERVED = {
    "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class",
    "const", "continue", "default", "do", "double", "else", "enum", "extends", "final",
    "finally", "float", "for", "goto", "if", "implements", "import", "instanceof", "int",
    "interface", "long", "native", "new", "package", "private", "protected", "public",
    "record", "return", "short", "static", "strictfp", "super", "switch", "synchronized",
    "this", "throw", "throws", "transient", "try", "void", "volatile", "while",
}


def java_name(name: str) -> str:
    return f"{name}Value" if name in JAVA_RESERVED else name


def emit_java_record(record: RecordType) -> str:
    lines = [f"package {JAVA_PACKAGE};", "", "import java.util.LinkedHashMap;", "import java.util.List;", "import java.util.Map;", ""]
    lines += java_doc(record.description, record.source)
    components = []
    for f in record.fields:
        marker = "@Required " if f.required else ""
        renamed = java_name(f.name)
        wire = f'@Wire("{f.name}") ' if renamed != f.name else ""
        components.append(
            f"        {marker}{wire}{Generator.java_field_type(f)} {renamed}"
        )
    lines.append(f"public record {record.name}(")
    lines.append(",\n".join(components))
    lines.append(") {")

    # toMap
    lines += [
        "",
        "    /**",
        "     * Convert to a JSON-compatible map. Absent optional fields are omitted rather",
        "     * than written as null (ADR-0020 §3).",
        "     */",
        "    public Map<String, Object> toMap() {",
        "        Map<String, Object> map = new LinkedHashMap<>();",
    ]
    for f in record.fields:
        expr = java_to_expr(f)
        if f.required:
            lines.append(f'        map.put("{f.name}", {expr});')
        else:
            lines.append(f"        if ({java_name(f.name)} != null) {{")
            lines.append(f'            map.put("{f.name}", {expr});')
            lines.append("        }")
    lines += ["        return map;", "    }", ""]

    # fromMap
    lines += [
        "    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */",
        f"    public static {record.name} fromMap(Map<String, Object> map) {{",
        f"        return new {record.name}(",
    ]
    args = []
    for f in record.fields:
        source = f'map.get("{f.name}")'
        conversion = java_from_expr(f, source)
        if f.required:
            args.append(f"                {conversion}")
        else:
            args.append(f"                {source} == null ? null : {conversion}")
    lines.append(",\n".join(args))
    lines += ["        );", "    }", ""]

    lines += [
        "    @SuppressWarnings(\"unchecked\")",
        "    private static <V> Map<String, V> asMap(Object value) {",
        "        return (Map<String, V>) value;",
        "    }",
        "",
        "    @SuppressWarnings(\"unchecked\")",
        "    private static <T> List<T> asList(Object value) {",
        "        return (List<T>) value;",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


PY_RESERVED = {"from", "import", "class", "def", "id", "type", "input", "return", "not", "in"}


def python_name(name: str) -> str:
    return f"{name}_" if name in PY_RESERVED else name


def python_from_expr(f: Field, source: str) -> str:
    t = f.type
    if t.kind == "enum":
        return f"{t.python}({source})"
    if t.kind == "record":
        return f"{t.python}.from_dict({source})"
    if t.kind == "list":
        inner = t.inner
        if inner is None or inner.kind not in ("record", "enum"):
            return f"list({source})"
        call = f"{inner.python}(_i)" if inner.kind == "enum" else f"{inner.python}.from_dict(_i)"
        return f"[{call} for _i in {source}]"
    if t.kind == "map":
        inner = t.inner
        if inner is None or inner.kind not in ("record", "enum"):
            return f"dict({source})"
        call = f"{inner.python}(_v)" if inner.kind == "enum" else f"{inner.python}.from_dict(_v)"
        return f"{{_k: {call} for _k, _v in {source}.items()}}"
    return source


def python_to_expr(f: Field, source: str) -> str:
    t = f.type
    if t.kind == "enum":
        return f"{source}.value"
    if t.kind == "record":
        return f"{source}.to_dict()"
    if t.kind == "list":
        inner = t.inner
        if inner is None or inner.kind not in ("record", "enum"):
            return f"list({source})"
        expr = "_i.value" if inner.kind == "enum" else "_i.to_dict()"
        return f"[{expr} for _i in {source}]"
    if t.kind == "map":
        inner = t.inner
        if inner is None or inner.kind not in ("record", "enum"):
            return f"dict({source})"
        expr = "_v.value" if inner.kind == "enum" else "_v.to_dict()"
        return f"{{_k: {expr} for _k, _v in {source}.items()}}"
    return source


def emit_python(generator: Generator) -> str:
    lines = [
        '"""Contract models generated from the canonical JSON Schemas.',
        "",
    ]
    for line in banner("schemas/**/*.schema.json"):
        lines.append(line)
    lines += [
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from enum import Enum",
        "from typing import Any",
        "",
        "__all__ = [",
    ]
    for name in sorted(list(generator.enums) + list(generator.records)):
        lines.append(f'    "{name}",')
    lines += ["]", ""]

    for name in sorted(generator.enums):
        enum = generator.enums[name]
        lines += ["", f"class {name}(str, Enum):", '    """']
        for line in wrap(enum.description or f"Generated from {enum.source}."):
            lines.append(f"    {line}")
        lines += [f"", f"    Source: {enum.source}", '    """', ""]
        for value in enum.values:
            constant = re.sub(r"[^0-9A-Za-z]+", "_", value).upper()
            if constant[:1].isdigit():
                constant = "_" + constant
            lines.append(f'    {constant} = "{value}"')
        lines.append("")

    for name in sorted(generator.records):
        record = generator.records[name]
        lines += ["", "@dataclass(frozen=True)", f"class {name}:", '    """']
        for line in wrap(record.description or f"Generated from {record.source}."):
            lines.append(f"    {line}")
        lines += ["", f"    Source: {record.source}", '    """', ""]
        if not record.fields:
            lines.append("    pass")
        for f in record.fields:
            annotation = f.type.python if f.required else f"{f.type.python} | None"
            default = "" if f.required else " = None"
            lines.append(f"    {python_name(f.name)}: {annotation}{default}")
        lines += [
            "",
            "    def to_dict(self) -> dict[str, Any]:",
            '        """Absent optional fields are omitted, never emitted as null'
            ' (ADR-0020 §3)."""',
            "        data: dict[str, Any] = {}",
        ]
        for f in record.fields:
            attr = f"self.{python_name(f.name)}"
            expr = python_to_expr(f, attr)
            if f.required:
                lines.append(f'        data["{f.name}"] = {expr}')
            else:
                lines.append(f"        if {attr} is not None:")
                lines.append(f'            data["{f.name}"] = {expr}')
        lines += [
            "        return data",
            "",
            "    @classmethod",
            f"    def from_dict(cls, data: dict[str, Any]) -> {name}:",
            '        """Performs no validation (ADR-0024 §4)."""',
            "        return cls(",
        ]
        for f in record.fields:
            source = f'data["{f.name}"]'
            expr = python_from_expr(f, source)
            if f.required:
                lines.append(f"            {python_name(f.name)}={expr},")
            else:
                guard = f'None if data.get("{f.name}") is None else '
                lines.append(f"            {python_name(f.name)}={guard}{expr},")
        lines += ["        )", ""]
    return "\n".join(lines) + "\n"


REQUIRED_ANNOTATION = """package io.aiplatform.contracts;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a record component that the source schema lists in {@code required}.
 *
 * This is metadata, not validation (ADR-0024 §4): nothing checks it at
 * construction time. It exists so that required-ness survives into the compiled
 * artifact, where the cross-language conformance check can compare it against
 * the Python models and the schema. Without it, an optional String and a
 * required String are indistinguishable by reflection, and the check would
 * silently verify nothing.
 *
 * Generated by .github/scripts/codegen.py.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.RECORD_COMPONENT, ElementType.PARAMETER})
public @interface Required {
}
"""

WIRE_ANNOTATION = """package io.aiplatform.contracts;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Records the JSON field name when it cannot be used as a Java identifier.
 *
 * Condition's {@code const} branch and CommandProfile's {@code default} parameter
 * are the cases that occur: both are Java keywords, so the generated components are
 * named {@code constValue} and {@code defaultValue}. The mapping is stated here
 * rather than inferred from a suffix convention, so that a field legitimately named
 * {@code somethingValue} is never mistaken for a renamed one.
 *
 * Generated by .github/scripts/codegen.py.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.RECORD_COMPONENT, ElementType.PARAMETER})
public @interface Wire {
    String value();
}
"""

POM = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  Contract models generated from schemas/**/*.schema.json (ADR-0024).

  Deliberately dependency-free in compile scope: generated records convert to and
  from java.util.Map rather than depending on a JSON binding library, so that
  consuming the contracts never forces a serialisation choice on the consumer.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.aiplatform</groupId>
  <artifactId>contracts</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>AI Engineering Platform contracts</name>
  <description>Generated Java models for the V1 domain contracts.</description>

  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
</project>
"""

PYPROJECT = """# Contract models generated from schemas/**/*.schema.json (ADR-0024).
#
# Deliberately dependency-free: generated dataclasses convert to and from plain
# dicts rather than depending on a validation or serialisation library, because
# validation is performed against the JSON Schema itself (ADR-0024 §4).

[project]
name = "aiplatform-contracts"
version = "1.0.0"
description = "Generated Python models for the V1 domain contracts."
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["aiplatform_contracts*"]
"""


def write(path: Path, content: str, outputs: dict[Path, str]) -> None:
    outputs[path] = content


def main(argv: list[str]) -> int:
    check = "--check" in argv
    documents = load_schemas()
    generator = Generator(documents)
    generator.run()

    outputs: dict[Path, str] = {}
    for name, enum in generator.enums.items():
        write(JAVA_SRC / f"{name}.java", emit_java_enum(enum), outputs)
    for name, record in generator.records.items():
        write(JAVA_SRC / f"{name}.java", emit_java_record(record), outputs)
    write(JAVA_SRC / "Required.java", REQUIRED_ANNOTATION, outputs)
    write(JAVA_SRC / "Wire.java", WIRE_ANNOTATION, outputs)
    write(JAVA_ROOT / "pom.xml", POM, outputs)
    write(PYTHON_PKG / "models.py", emit_python(generator), outputs)
    write(
        PYTHON_PKG / "__init__.py",
        '"""Generated contract models. See models.py."""\n\nfrom aiplatform_contracts.models import *  # noqa: F401,F403\n',
        outputs,
    )
    write(PYTHON_ROOT / "pyproject.toml", PYPROJECT, outputs)

    if check:
        problems: list[str] = []
        existing = {
            p.resolve()
            for p in list(JAVA_SRC.rglob("*.java")) + list(PYTHON_PKG.rglob("*.py"))
        }
        for path, content in outputs.items():
            if not path.exists():
                problems.append(f"missing generated file: {path.relative_to(ROOT)}")
            elif path.read_text(encoding="utf-8") != content:
                problems.append(f"out of date: {path.relative_to(ROOT)}")
        for path in sorted(existing - {p.resolve() for p in outputs}):
            problems.append(f"orphaned generated file: {path.relative_to(ROOT)}")
        if problems:
            print("codegen --check: generated code does not match the schemas")
            for problem in problems:
                print(f"  {problem}")
            print("\n  Run: python3 .github/scripts/codegen.py")
            return 1
        print(
            f"codegen --check: {len(outputs)} generated files match the schemas "
            f"({len(generator.records)} records, {len(generator.enums)} enums)"
        )
        return 0

    for stale in list(JAVA_SRC.rglob("*.java")):
        if stale.resolve() not in {p.resolve() for p in outputs}:
            stale.unlink()
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(
        f"codegen: wrote {len(outputs)} files "
        f"({len(generator.records)} records, {len(generator.enums)} enums)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
