package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * An immutable, content-addressed agent definition (ADR-0022 §1). An Agent is declarative
 * data, never code. Editing one produces a new version rather than mutating the existing
 * definition, because a run pins a version for its entire life and an in-place edit would
 * silently change the behaviour of work already in flight. The definition deliberately omits
 * the objective and the output schema: those are per-node, live in the Graph, and are already
 * pinned by graphVersionHash (ADR-0022 §2). An agent is reusable behaviour; a node is one
 * specific use of it.
 *
 * Generated by .github/scripts/codegen.py from schemas/agent/agent.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record Agent(
        @Required String schemaVersion,
        @Required String agentId,
        @Required String title,
        @Required String description,
        @Required List<String> systemInstructions,
        @Required AgentDefaultModelPolicy defaultModelPolicy,
        @Required AgentDefaultBudgets defaultBudgets,
        @Required AgentCapabilityCeiling capabilityCeiling,
        @Required AgentOutputContractStyle outputContractStyle,
        String agentVersionHash
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("agentId", agentId);
        map.put("title", title);
        map.put("description", description);
        map.put("systemInstructions", systemInstructions);
        map.put("defaultModelPolicy", defaultModelPolicy.toMap());
        map.put("defaultBudgets", defaultBudgets.toMap());
        map.put("capabilityCeiling", capabilityCeiling.toMap());
        map.put("outputContractStyle", outputContractStyle.wire());
        if (agentVersionHash != null) {
            map.put("agentVersionHash", agentVersionHash);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static Agent fromMap(Map<String, Object> map) {
        return new Agent(
                (String) map.get("schemaVersion"),
                (String) map.get("agentId"),
                (String) map.get("title"),
                (String) map.get("description"),
                asList(map.get("systemInstructions")),
                AgentDefaultModelPolicy.fromMap(asMap(map.get("defaultModelPolicy"))),
                AgentDefaultBudgets.fromMap(asMap(map.get("defaultBudgets"))),
                AgentCapabilityCeiling.fromMap(asMap(map.get("capabilityCeiling"))),
                AgentOutputContractStyle.fromWire((String) map.get("outputContractStyle")),
                map.get("agentVersionHash") == null ? null : (String) map.get("agentVersionHash")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
