package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/agent/agent-execution-request.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record AgentExecutionRequestBudgets(
        @Required long maxIterations,
        @Required long maxTokens,
        @Required String deadline,
        Long maxRetrievals,
        Long maxCostUnits
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("maxIterations", maxIterations);
        map.put("maxTokens", maxTokens);
        map.put("deadline", deadline);
        if (maxRetrievals != null) {
            map.put("maxRetrievals", maxRetrievals);
        }
        if (maxCostUnits != null) {
            map.put("maxCostUnits", maxCostUnits);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static AgentExecutionRequestBudgets fromMap(Map<String, Object> map) {
        return new AgentExecutionRequestBudgets(
                ((Number) map.get("maxIterations")).longValue(),
                ((Number) map.get("maxTokens")).longValue(),
                (String) map.get("deadline"),
                map.get("maxRetrievals") == null ? null : ((Number) map.get("maxRetrievals")).longValue(),
                map.get("maxCostUnits") == null ? null : ((Number) map.get("maxCostUnits")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
