package io.aiplatform.contracts;

/**
 * Maps onto the failure categories of ADR-0008. The runtime does not invent categories and
 * does not decide retryability.
 *
 * Generated by .github/scripts/codegen.py from schemas/agent/agent-execution-result.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum AgentExecutionResultStatus {
    COMPLETED("COMPLETED"),
    BUDGET_EXHAUSTED("BUDGET_EXHAUSTED"),
    MODEL_ERROR("MODEL_ERROR"),
    TOOL_ERROR("TOOL_ERROR"),
    RUNTIME_ERROR("RUNTIME_ERROR"),
    CANCELLED("CANCELLED");

    private final String wire;

    AgentExecutionResultStatus(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static AgentExecutionResultStatus fromWire(String value) {
        for (AgentExecutionResultStatus candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown AgentExecutionResultStatus value: " + value);
    }
}
