package io.aiplatform.contracts;

/**
 * STRUCTURED: the agent is expected to produce output validating against the node's declared
 * output schema. FREEFORM: prose, permissible only where no downstream transition depends on
 * the shape.
 *
 * Generated by .github/scripts/codegen.py from schemas/agent/agent.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum AgentOutputContractStyle {
    STRUCTURED("STRUCTURED"),
    FREEFORM("FREEFORM");

    private final String wire;

    AgentOutputContractStyle(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static AgentOutputContractStyle fromWire(String value) {
        for (AgentOutputContractStyle candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown AgentOutputContractStyle value: " + value);
    }
}
