package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * POST /v1/agent-executions, control plane to agent runtime (ADR-0004 §11). One call, exactly
 * one node attempt. The runtime never selects the next node, never decides to retry, never
 * branches and never schedules work; all workflow control lives in the graph engine.
 *
 * Generated by .github/scripts/codegen.py from schemas/agent/agent-execution-request.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record AgentExecutionRequest(
        @Required String protocolVersion,
        @Required String runId,
        @Required String nodeId,
        @Required long iteration,
        @Required long attempt,
        @Required String agentId,
        @Required String agentVersionHash,
        @Required String objective,
        @Required List<String> instructions,
        @Required String contextBundleRef,
        @Required List<Tool> tools,
        @Required Map<String, Object> outputSchema,
        @Required AgentExecutionRequestBudgets budgets,
        @Required String callbackToken,
        String traceparent,
        AgentExecutionRequestModelPolicy modelPolicy
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("protocolVersion", protocolVersion);
        map.put("runId", runId);
        map.put("nodeId", nodeId);
        map.put("iteration", iteration);
        map.put("attempt", attempt);
        map.put("agentId", agentId);
        map.put("agentVersionHash", agentVersionHash);
        map.put("objective", objective);
        map.put("instructions", instructions);
        map.put("contextBundleRef", contextBundleRef);
        map.put("tools", tools.stream().map(Tool::toMap).toList());
        map.put("outputSchema", outputSchema);
        map.put("budgets", budgets.toMap());
        map.put("callbackToken", callbackToken);
        if (traceparent != null) {
            map.put("traceparent", traceparent);
        }
        if (modelPolicy != null) {
            map.put("modelPolicy", modelPolicy.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static AgentExecutionRequest fromMap(Map<String, Object> map) {
        return new AgentExecutionRequest(
                (String) map.get("protocolVersion"),
                (String) map.get("runId"),
                (String) map.get("nodeId"),
                ((Number) map.get("iteration")).longValue(),
                ((Number) map.get("attempt")).longValue(),
                (String) map.get("agentId"),
                (String) map.get("agentVersionHash"),
                (String) map.get("objective"),
                asList(map.get("instructions")),
                (String) map.get("contextBundleRef"),
                asList(map.get("tools")).stream().map(e -> Tool.fromMap(asMap(e))).toList(),
                (Map<String, Object>) map.get("outputSchema"),
                AgentExecutionRequestBudgets.fromMap(asMap(map.get("budgets"))),
                (String) map.get("callbackToken"),
                map.get("traceparent") == null ? null : (String) map.get("traceparent"),
                map.get("modelPolicy") == null ? null : AgentExecutionRequestModelPolicy.fromMap(asMap(map.get("modelPolicy")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
