package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Returned by the agent runtime for one node attempt (ADR-0004 §11). ADR-0004 §9: the control
 * plane never trusts this self-report. claimedOutput is validated against the node's declared
 * output schema before any transition is evaluated; usage and cost are taken from the model
 * gateway's own records rather than from the runtime's summary; tool effects are known from
 * the tool layer's records rather than from the runtime's narrative. That is what makes this a
 * trust boundary rather than a module boundary.
 *
 * Generated by .github/scripts/codegen.py from schemas/agent/agent-execution-result.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record AgentExecutionResult(
        @Required String protocolVersion,
        @Required AgentExecutionResultStatus status,
        @Required long agentLoopIterations,
        Map<String, Object> claimedOutput,
        String stopReason,
        AgentExecutionResultFailure failure
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("protocolVersion", protocolVersion);
        map.put("status", status.wire());
        map.put("agentLoopIterations", agentLoopIterations);
        if (claimedOutput != null) {
            map.put("claimedOutput", claimedOutput);
        }
        if (stopReason != null) {
            map.put("stopReason", stopReason);
        }
        if (failure != null) {
            map.put("failure", failure.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static AgentExecutionResult fromMap(Map<String, Object> map) {
        return new AgentExecutionResult(
                (String) map.get("protocolVersion"),
                AgentExecutionResultStatus.fromWire((String) map.get("status")),
                ((Number) map.get("agentLoopIterations")).longValue(),
                map.get("claimedOutput") == null ? null : (Map<String, Object>) map.get("claimedOutput"),
                map.get("stopReason") == null ? null : (String) map.get("stopReason"),
                map.get("failure") == null ? null : AgentExecutionResultFailure.fromMap(asMap(map.get("failure")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
