package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The most this agent may ever be granted, extending the derivation chain of ADR-0014 §5:
 * platform policy contains trust-level ceiling contains registry record contains agent ceiling
 * contains node request. Monotonically non-increasing at every step. Its value is that a
 * general-purpose agent can be denied IRREVERSIBLE tools once, centrally, instead of in every
 * node that uses it. Validated against platform policy at publication (ADR-0022 §6), so an
 * over-broad agent cannot be published and then discovered in production.
 *
 * Generated by .github/scripts/codegen.py from schemas/agent/agent.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record AgentCapabilityCeiling(
        @Required List<String> allowedTools,
        @Required SideEffectClass maxSideEffect,
        List<String> commandProfiles
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("allowedTools", allowedTools);
        map.put("maxSideEffect", maxSideEffect.wire());
        if (commandProfiles != null) {
            map.put("commandProfiles", commandProfiles);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static AgentCapabilityCeiling fromMap(Map<String, Object> map) {
        return new AgentCapabilityCeiling(
                asList(map.get("allowedTools")),
                SideEffectClass.fromWire((String) map.get("maxSideEffect")),
                map.get("commandProfiles") == null ? null : asList(map.get("commandProfiles"))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
