package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A human decision on a consequential action (ADR-0009). The record binds to subjectHash — the
 * content hash of exactly what was approved — and the engine re-verifies it on resume. Without
 * that binding an approval is a time-of-check/time-of-use bug with a human in it.
 *
 * Generated by .github/scripts/codegen.py from schemas/approval/approval.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record Approval(
        @Required String schemaVersion,
        @Required String approvalId,
        @Required String runId,
        @Required String nodeId,
        @Required ApprovalKind kind,
        @Required ApprovalRequiredKind requiredKind,
        @Required String subjectHash,
        @Required ArtifactRef subjectRef,
        @Required String renderingHash,
        @Required ApprovalStatus status,
        @Required String expiresAt,
        @Required boolean interactive,
        @Required String createdAt,
        String decidedBy,
        String decidedAt,
        String reRequestOf,
        String externalRef,
        String rationale
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("approvalId", approvalId);
        map.put("runId", runId);
        map.put("nodeId", nodeId);
        map.put("kind", kind.wire());
        map.put("requiredKind", requiredKind.wire());
        map.put("subjectHash", subjectHash);
        map.put("subjectRef", subjectRef.toMap());
        map.put("renderingHash", renderingHash);
        map.put("status", status.wire());
        map.put("expiresAt", expiresAt);
        map.put("interactive", interactive);
        map.put("createdAt", createdAt);
        if (decidedBy != null) {
            map.put("decidedBy", decidedBy);
        }
        if (decidedAt != null) {
            map.put("decidedAt", decidedAt);
        }
        if (reRequestOf != null) {
            map.put("reRequestOf", reRequestOf);
        }
        if (externalRef != null) {
            map.put("externalRef", externalRef);
        }
        if (rationale != null) {
            map.put("rationale", rationale);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static Approval fromMap(Map<String, Object> map) {
        return new Approval(
                (String) map.get("schemaVersion"),
                (String) map.get("approvalId"),
                (String) map.get("runId"),
                (String) map.get("nodeId"),
                ApprovalKind.fromWire((String) map.get("kind")),
                ApprovalRequiredKind.fromWire((String) map.get("requiredKind")),
                (String) map.get("subjectHash"),
                ArtifactRef.fromMap(asMap(map.get("subjectRef"))),
                (String) map.get("renderingHash"),
                ApprovalStatus.fromWire((String) map.get("status")),
                (String) map.get("expiresAt"),
                (Boolean) map.get("interactive"),
                (String) map.get("createdAt"),
                map.get("decidedBy") == null ? null : (String) map.get("decidedBy"),
                map.get("decidedAt") == null ? null : (String) map.get("decidedAt"),
                map.get("reRequestOf") == null ? null : (String) map.get("reRequestOf"),
                map.get("externalRef") == null ? null : (String) map.get("externalRef"),
                map.get("rationale") == null ? null : (String) map.get("rationale")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
