package io.aiplatform.contracts;

/**
 * LOCAL_OPERATOR_CONSENT is self-asserted: the platform can attest that someone at the
 * keyboard consented, not who they were. EXTERNAL_ATTESTATION borrows identity from a system
 * that has it — a GitHub review, a Jira transition — and is the stronger form precisely
 * because the platform is not the one asserting it.
 *
 * Generated by .github/scripts/codegen.py from schemas/approval/approval.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ApprovalKind {
    LOCAL_OPERATOR_CONSENT("LOCAL_OPERATOR_CONSENT"),
    EXTERNAL_ATTESTATION("EXTERNAL_ATTESTATION");

    private final String wire;

    ApprovalKind(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ApprovalKind fromWire(String value) {
        for (ApprovalKind candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ApprovalKind value: " + value);
    }
}
