package io.aiplatform.contracts;

/**
 * What policy demanded, computed as the strictest of the tool's side-effect class, the
 * repository trust level and the graph node definition (ADR-0009 §2). Any layer may require a
 * stronger kind; none may require a weaker one.
 *
 * Generated by .github/scripts/codegen.py from schemas/approval/approval.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ApprovalRequiredKind {
    LOCAL_OPERATOR_CONSENT("LOCAL_OPERATOR_CONSENT"),
    EXTERNAL_ATTESTATION("EXTERNAL_ATTESTATION");

    private final String wire;

    ApprovalRequiredKind(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ApprovalRequiredKind fromWire(String value) {
        for (ApprovalRequiredKind candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ApprovalRequiredKind value: " + value);
    }
}
