package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/artifacts/artifact-ref.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ArtifactRefClassificationArtifactType {
    TRANSCRIPT("TRANSCRIPT"),
    PROMPT("PROMPT"),
    COMPLETION("COMPLETION"),
    CONTEXT_BUNDLE("CONTEXT_BUNDLE"),
    PATCH("PATCH"),
    BUILD_LOG("BUILD_LOG"),
    CI_LOG("CI_LOG"),
    TOOL_OUTPUT("TOOL_OUTPUT"),
    EVALUATION("EVALUATION"),
    REPORT("REPORT"),
    AUDIT_EXPORT("AUDIT_EXPORT");

    private final String wire;

    ArtifactRefClassificationArtifactType(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ArtifactRefClassificationArtifactType fromWire(String value) {
        for (ArtifactRefClassificationArtifactType candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ArtifactRefClassificationArtifactType value: " + value);
    }
}
