package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/artifacts/artifact-ref.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ArtifactRefClassificationRetentionTier {
    EPHEMERAL("EPHEMERAL"),
    RUN_LIFECYCLE("RUN_LIFECYCLE"),
    REPRODUCIBILITY("REPRODUCIBILITY"),
    AUDIT("AUDIT");

    private final String wire;

    ArtifactRefClassificationRetentionTier(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ArtifactRefClassificationRetentionTier fromWire(String value) {
        for (ArtifactRefClassificationRetentionTier candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ArtifactRefClassificationRetentionTier value: " + value);
    }
}
