package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/artifacts/artifact-ref.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ArtifactRefClassificationSensitivity {
    PUBLIC("PUBLIC"),
    INTERNAL("INTERNAL"),
    SENSITIVE("SENSITIVE");

    private final String wire;

    ArtifactRefClassificationSensitivity(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ArtifactRefClassificationSensitivity fromWire(String value) {
        for (ArtifactRefClassificationSensitivity candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ArtifactRefClassificationSensitivity value: " + value);
    }
}
