package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A reference to content in the artifact store (ADR-0017 §2). ADR-0003 §3 requires that
 * artifacts cross the execution boundary as references and never as local paths or open
 * handles, so this type appears in most other contracts.
 *
 * Generated by .github/scripts/codegen.py from schemas/artifacts/artifact-ref.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ArtifactRef(
        @Required String uri,
        @Required String sha256,
        @Required long sizeBytes,
        @Required String contentType,
        @Required ArtifactRefClassification classification,
        @Required String createdAt,
        ArtifactRefEncoding encoding,
        String expiresAt
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("uri", uri);
        map.put("sha256", sha256);
        map.put("sizeBytes", sizeBytes);
        map.put("contentType", contentType);
        map.put("classification", classification.toMap());
        map.put("createdAt", createdAt);
        if (encoding != null) {
            map.put("encoding", encoding.wire());
        }
        if (expiresAt != null) {
            map.put("expiresAt", expiresAt);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ArtifactRef fromMap(Map<String, Object> map) {
        return new ArtifactRef(
                (String) map.get("uri"),
                (String) map.get("sha256"),
                ((Number) map.get("sizeBytes")).longValue(),
                (String) map.get("contentType"),
                ArtifactRefClassification.fromMap(asMap(map.get("classification"))),
                (String) map.get("createdAt"),
                map.get("encoding") == null ? null : ArtifactRefEncoding.fromWire((String) map.get("encoding")),
                map.get("expiresAt") == null ? null : (String) map.get("expiresAt")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
