package io.aiplatform.contracts;

/**
 * ADR-0016 §3. SELF_ASSERTED: the platform states it about itself and a local attacker could
 * forge it. PLATFORM_ATTESTED: produced by a control-plane component and hash-chained.
 * EXTERNALLY_VERIFIABLE: corroborated by a system outside this machine, such as a GitHub
 * commit or a Jira transition. V1 is developer-attested and is not adversarial-grade; the
 * field exists so that nobody later mistakes it for something stronger.
 *
 * Generated by .github/scripts/codegen.py from schemas/audit/audit-entry.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum AuditEntryAssurance {
    SELF_ASSERTED("SELF_ASSERTED"),
    PLATFORM_ATTESTED("PLATFORM_ATTESTED"),
    EXTERNALLY_VERIFIABLE("EXTERNALLY_VERIFIABLE");

    private final String wire;

    AuditEntryAssurance(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static AuditEntryAssurance fromWire(String value) {
        for (AuditEntryAssurance candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown AuditEntryAssurance value: " + value);
    }
}
