package io.aiplatform.contracts;

/**
 * INDETERMINATE records that a write-ahead intent exists with no matching outcome. It is the
 * only honest answer available after a crash mid-side-effect, and ADR-0008 §7 forbids
 * auto-retrying it.
 *
 * Generated by .github/scripts/codegen.py from schemas/audit/audit-entry.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum AuditEntryDecision {
    ALLOWED("ALLOWED"),
    DENIED("DENIED"),
    INDETERMINATE("INDETERMINATE");

    private final String wire;

    AuditEntryDecision(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static AuditEntryDecision fromWire(String value) {
        for (AuditEntryDecision candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown AuditEntryDecision value: " + value);
    }
}
