package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/audit/audit-entry.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record AuditEntryActor(
        @Required String localUser,
        @Required String platformInstanceId,
        @Required String initiatedBy,
        String externalIdentity
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("localUser", localUser);
        map.put("platformInstanceId", platformInstanceId);
        map.put("initiatedBy", initiatedBy);
        if (externalIdentity != null) {
            map.put("externalIdentity", externalIdentity);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static AuditEntryActor fromMap(Map<String, Object> map) {
        return new AuditEntryActor(
                (String) map.get("localUser"),
                (String) map.get("platformInstanceId"),
                (String) map.get("initiatedBy"),
                map.get("externalIdentity") == null ? null : (String) map.get("externalIdentity")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
