package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * An append-only record of an attempted consequential action (ADR-0016). Written fail-closed:
 * if the entry cannot be persisted, the action does not proceed. Retained independently of
 * telemetry — traces may be sampled and logs may be dropped, audit may not. ADR-0016 is
 * explicit about the limits of what V1 can attest to; see the assurance field.
 *
 * Generated by .github/scripts/codegen.py from schemas/audit/audit-entry.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record AuditEntry(
        @Required String schemaVersion,
        @Required String auditId,
        @Required long sequence,
        @Required String timestamp,
        @Required String runId,
        @Required String action,
        @Required AuditEntryDecision decision,
        @Required AuditEntryAssurance assurance,
        @Required AuditEntryActor actor,
        @Required String prevHash,
        @Required String entryHash,
        String nodeId,
        Long attempt,
        Long iteration,
        String graphId,
        String graphVersionHash,
        String agentId,
        String subjectRef,
        String subjectHash,
        SideEffectClass sideEffectClass,
        String capabilityGrantId,
        String reason,
        String externalRef,
        String traceId,
        String spanId
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("auditId", auditId);
        map.put("sequence", sequence);
        map.put("timestamp", timestamp);
        map.put("runId", runId);
        map.put("action", action);
        map.put("decision", decision.wire());
        map.put("assurance", assurance.wire());
        map.put("actor", actor.toMap());
        map.put("prevHash", prevHash);
        map.put("entryHash", entryHash);
        if (nodeId != null) {
            map.put("nodeId", nodeId);
        }
        if (attempt != null) {
            map.put("attempt", attempt);
        }
        if (iteration != null) {
            map.put("iteration", iteration);
        }
        if (graphId != null) {
            map.put("graphId", graphId);
        }
        if (graphVersionHash != null) {
            map.put("graphVersionHash", graphVersionHash);
        }
        if (agentId != null) {
            map.put("agentId", agentId);
        }
        if (subjectRef != null) {
            map.put("subjectRef", subjectRef);
        }
        if (subjectHash != null) {
            map.put("subjectHash", subjectHash);
        }
        if (sideEffectClass != null) {
            map.put("sideEffectClass", sideEffectClass.wire());
        }
        if (capabilityGrantId != null) {
            map.put("capabilityGrantId", capabilityGrantId);
        }
        if (reason != null) {
            map.put("reason", reason);
        }
        if (externalRef != null) {
            map.put("externalRef", externalRef);
        }
        if (traceId != null) {
            map.put("traceId", traceId);
        }
        if (spanId != null) {
            map.put("spanId", spanId);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static AuditEntry fromMap(Map<String, Object> map) {
        return new AuditEntry(
                (String) map.get("schemaVersion"),
                (String) map.get("auditId"),
                ((Number) map.get("sequence")).longValue(),
                (String) map.get("timestamp"),
                (String) map.get("runId"),
                (String) map.get("action"),
                AuditEntryDecision.fromWire((String) map.get("decision")),
                AuditEntryAssurance.fromWire((String) map.get("assurance")),
                AuditEntryActor.fromMap(asMap(map.get("actor"))),
                (String) map.get("prevHash"),
                (String) map.get("entryHash"),
                map.get("nodeId") == null ? null : (String) map.get("nodeId"),
                map.get("attempt") == null ? null : ((Number) map.get("attempt")).longValue(),
                map.get("iteration") == null ? null : ((Number) map.get("iteration")).longValue(),
                map.get("graphId") == null ? null : (String) map.get("graphId"),
                map.get("graphVersionHash") == null ? null : (String) map.get("graphVersionHash"),
                map.get("agentId") == null ? null : (String) map.get("agentId"),
                map.get("subjectRef") == null ? null : (String) map.get("subjectRef"),
                map.get("subjectHash") == null ? null : (String) map.get("subjectHash"),
                map.get("sideEffectClass") == null ? null : SideEffectClass.fromWire((String) map.get("sideEffectClass")),
                map.get("capabilityGrantId") == null ? null : (String) map.get("capabilityGrantId"),
                map.get("reason") == null ? null : (String) map.get("reason"),
                map.get("externalRef") == null ? null : (String) map.get("externalRef"),
                map.get("traceId") == null ? null : (String) map.get("traceId"),
                map.get("spanId") == null ? null : (String) map.get("spanId")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
