package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/tools/capability-grant.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record CapabilityGrantBudget(
        @Required long maxInvocations,
        @Required long maxWallClockMs,
        @Required long maxDenials,
        Long maxCostUnits
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("maxInvocations", maxInvocations);
        map.put("maxWallClockMs", maxWallClockMs);
        map.put("maxDenials", maxDenials);
        if (maxCostUnits != null) {
            map.put("maxCostUnits", maxCostUnits);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static CapabilityGrantBudget fromMap(Map<String, Object> map) {
        return new CapabilityGrantBudget(
                ((Number) map.get("maxInvocations")).longValue(),
                ((Number) map.get("maxWallClockMs")).longValue(),
                ((Number) map.get("maxDenials")).longValue(),
                map.get("maxCostUnits") == null ? null : ((Number) map.get("maxCostUnits")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
