package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/tools/capability-grant.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record CapabilityGrantExternalScope(
        List<String> jiraProjectKeys,
        List<String> githubRepositories,
        List<String> confluenceSpaceKeys
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (jiraProjectKeys != null) {
            map.put("jiraProjectKeys", jiraProjectKeys);
        }
        if (githubRepositories != null) {
            map.put("githubRepositories", githubRepositories);
        }
        if (confluenceSpaceKeys != null) {
            map.put("confluenceSpaceKeys", confluenceSpaceKeys);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static CapabilityGrantExternalScope fromMap(Map<String, Object> map) {
        return new CapabilityGrantExternalScope(
                map.get("jiraProjectKeys") == null ? null : asList(map.get("jiraProjectKeys")),
                map.get("githubRepositories") == null ? null : asList(map.get("githubRepositories")),
                map.get("confluenceSpaceKeys") == null ? null : asList(map.get("confluenceSpaceKeys"))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
