package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The NodeRun attempt this grant authorises, using the four-part key of ADR-0021 §1. iteration
 * is required: without it, two attempts in different loop rounds would share a subject.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/capability-grant.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record CapabilityGrantSubject(
        @Required String runId,
        @Required String nodeId,
        @Required long iteration,
        @Required long attempt
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("runId", runId);
        map.put("nodeId", nodeId);
        map.put("iteration", iteration);
        map.put("attempt", attempt);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static CapabilityGrantSubject fromMap(Map<String, Object> map) {
        return new CapabilityGrantSubject(
                (String) map.get("runId"),
                (String) map.get("nodeId"),
                ((Number) map.get("iteration")).longValue(),
                ((Number) map.get("attempt")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
