package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Minted by the control plane per node attempt (ADR-0005 §4). Derived from the graph node
 * definition intersected with the repository registry's capability ceiling, never from
 * anything the model produced. Monotonically non-increasing: no operation grows a grant
 * mid-attempt, and a retry receives a fresh grant so a failed attempt leaves no residual
 * authority. The agent runtime never handles a grant, only the attempt token that resolves to
 * it.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/capability-grant.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record CapabilityGrant(
        @Required String schemaVersion,
        @Required String grantId,
        @Required CapabilityGrantSubject subject,
        @Required List<CapabilityGrantAllowedToolsItem> allowedTools,
        @Required SideEffectClass maxSideEffect,
        @Required List<String> repositoryScope,
        @Required Map<String, PathScopeEntry> pathScope,
        @Required CapabilityGrantBudget budget,
        @Required String notAfter,
        CapabilityGrantExternalScope externalScope,
        List<String> commandProfiles
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("grantId", grantId);
        map.put("subject", subject.toMap());
        map.put("allowedTools", allowedTools.stream().map(CapabilityGrantAllowedToolsItem::toMap).toList());
        map.put("maxSideEffect", maxSideEffect.wire());
        map.put("repositoryScope", repositoryScope);
        map.put("pathScope", pathScope.entrySet().stream().collect(java.util.stream.Collectors.toMap(java.util.Map.Entry::getKey, e -> e.getValue().toMap())));
        map.put("budget", budget.toMap());
        map.put("notAfter", notAfter);
        if (externalScope != null) {
            map.put("externalScope", externalScope.toMap());
        }
        if (commandProfiles != null) {
            map.put("commandProfiles", commandProfiles);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static CapabilityGrant fromMap(Map<String, Object> map) {
        return new CapabilityGrant(
                (String) map.get("schemaVersion"),
                (String) map.get("grantId"),
                CapabilityGrantSubject.fromMap(asMap(map.get("subject"))),
                asList(map.get("allowedTools")).stream().map(e -> CapabilityGrantAllowedToolsItem.fromMap(asMap(e))).toList(),
                SideEffectClass.fromWire((String) map.get("maxSideEffect")),
                asList(map.get("repositoryScope")),
                asMap(map.get("pathScope")).entrySet().stream().collect(java.util.stream.Collectors.toMap(java.util.Map.Entry::getKey, e -> PathScopeEntry.fromMap(asMap(e.getValue())))),
                CapabilityGrantBudget.fromMap(asMap(map.get("budget"))),
                (String) map.get("notAfter"),
                map.get("externalScope") == null ? null : CapabilityGrantExternalScope.fromMap(asMap(map.get("externalScope"))),
                map.get("commandProfiles") == null ? null : asList(map.get("commandProfiles"))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
