package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Written at every node boundary, in the same transactional batch as the node's terminal
 * status (ADR-0008 §10). Intra-agent iteration checkpoints are explicitly out of scope: an
 * agent attempt is the unit of retry, and a partially completed agent loop is re-run, not
 * resumed.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/checkpoint.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record Checkpoint(
        @Required String schemaVersion,
        @Required String checkpointId,
        @Required String runId,
        @Required String afterNodeId,
        @Required long afterIteration,
        @Required long afterAttempt,
        @Required long sequence,
        @Required CheckpointWorkspaceState workspaceStateRef,
        @Required String createdAt,
        ArtifactRef graphVariablesRef,
        List<String> contextBundleRefs
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("checkpointId", checkpointId);
        map.put("runId", runId);
        map.put("afterNodeId", afterNodeId);
        map.put("afterIteration", afterIteration);
        map.put("afterAttempt", afterAttempt);
        map.put("sequence", sequence);
        map.put("workspaceStateRef", workspaceStateRef.toMap());
        map.put("createdAt", createdAt);
        if (graphVariablesRef != null) {
            map.put("graphVariablesRef", graphVariablesRef.toMap());
        }
        if (contextBundleRefs != null) {
            map.put("contextBundleRefs", contextBundleRefs);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static Checkpoint fromMap(Map<String, Object> map) {
        return new Checkpoint(
                (String) map.get("schemaVersion"),
                (String) map.get("checkpointId"),
                (String) map.get("runId"),
                (String) map.get("afterNodeId"),
                ((Number) map.get("afterIteration")).longValue(),
                ((Number) map.get("afterAttempt")).longValue(),
                ((Number) map.get("sequence")).longValue(),
                CheckpointWorkspaceState.fromMap(asMap(map.get("workspaceStateRef"))),
                (String) map.get("createdAt"),
                map.get("graphVariablesRef") == null ? null : ArtifactRef.fromMap(asMap(map.get("graphVariablesRef"))),
                map.get("contextBundleRefs") == null ? null : asList(map.get("contextBundleRefs"))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
