package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The load-bearing invariant of ADR-0003 §6: workspace state is at all times a function of
 * (repoRef, baseSHA, ordered patch series), all of which live in durable state. This is
 * simultaneously what makes resume work and what makes a remote executor a drop-in. Without
 * it, workspaces become precious mutable state on one laptop and both properties are lost.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/checkpoint.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record CheckpointWorkspaceState(
        @Required List<CheckpointWorkspaceStateRepositoriesItem> repositories
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("repositories", repositories.stream().map(CheckpointWorkspaceStateRepositoriesItem::toMap).toList());
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static CheckpointWorkspaceState fromMap(Map<String, Object> map) {
        return new CheckpointWorkspaceState(
                asList(map.get("repositories")).stream().map(e -> CheckpointWorkspaceStateRepositoriesItem.fromMap(asMap(e))).toList()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
