package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/graph/checkpoint.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record CheckpointWorkspaceStateRepositoriesItem(
        @Required RepoRef repoRef,
        @Required String baseSha,
        @Required List<ArtifactRef> patchSeries
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("repoRef", repoRef.toMap());
        map.put("baseSha", baseSha);
        map.put("patchSeries", patchSeries.stream().map(ArtifactRef::toMap).toList());
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static CheckpointWorkspaceStateRepositoriesItem fromMap(Map<String, Object> map) {
        return new CheckpointWorkspaceStateRepositoriesItem(
                RepoRef.fromMap(asMap(map.get("repoRef"))),
                (String) map.get("baseSha"),
                asList(map.get("patchSeries")).stream().map(e -> ArtifactRef.fromMap(asMap(e))).toList()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
