package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/tools/command-profile.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record CommandProfileParametersItem(
        @Required String name,
        @Required CommandProfileParametersItemType type,
        @Required boolean required,
        String pattern,
        List<String> allowedValues,
        @Wire("default") Object defaultValue
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("name", name);
        map.put("type", type.wire());
        map.put("required", required);
        if (pattern != null) {
            map.put("pattern", pattern);
        }
        if (allowedValues != null) {
            map.put("allowedValues", allowedValues);
        }
        if (defaultValue != null) {
            map.put("default", defaultValue);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static CommandProfileParametersItem fromMap(Map<String, Object> map) {
        return new CommandProfileParametersItem(
                (String) map.get("name"),
                CommandProfileParametersItemType.fromWire((String) map.get("type")),
                (Boolean) map.get("required"),
                map.get("pattern") == null ? null : (String) map.get("pattern"),
                map.get("allowedValues") == null ? null : asList(map.get("allowedValues")),
                map.get("default") == null ? null : (Object) map.get("default")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
