package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A named, argv-fixed command declared by a repository (ADR-0005 §5).
 * workspace.run_profile(profileId, parameters) is the only route to command execution: there
 * is no tool that accepts a shell string or a free-form argv array from a model. Parameters
 * are substituted as discrete argv elements, never concatenated into a shell, and no shell is
 * involved at any layer.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/command-profile.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record CommandProfile(
        @Required String schemaVersion,
        @Required String profileId,
        @Required String description,
        @Required List<String> argv,
        @Required List<CommandProfileParametersItem> parameters,
        @Required List<String> cwdScope,
        @Required long timeoutMs,
        @Required ResourceLimits resourceLimits,
        @Required NetworkPolicy networkPolicy,
        @Required String sideEffectClass
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("profileId", profileId);
        map.put("description", description);
        map.put("argv", argv);
        map.put("parameters", parameters.stream().map(CommandProfileParametersItem::toMap).toList());
        map.put("cwdScope", cwdScope);
        map.put("timeoutMs", timeoutMs);
        map.put("resourceLimits", resourceLimits.toMap());
        map.put("networkPolicy", networkPolicy.toMap());
        map.put("sideEffectClass", sideEffectClass);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static CommandProfile fromMap(Map<String, Object> map) {
        return new CommandProfile(
                (String) map.get("schemaVersion"),
                (String) map.get("profileId"),
                (String) map.get("description"),
                asList(map.get("argv")),
                asList(map.get("parameters")).stream().map(e -> CommandProfileParametersItem.fromMap(asMap(e))).toList(),
                asList(map.get("cwdScope")),
                ((Number) map.get("timeoutMs")).longValue(),
                ResourceLimits.fromMap(asMap(map.get("resourceLimits"))),
                NetworkPolicy.fromMap(asMap(map.get("networkPolicy"))),
                (String) map.get("sideEffectClass")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
