package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Union of mutually exclusive branches; exactly one branch's required fields are present in a
 * valid document, which the JSON Schema enforces and this type does not.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/condition.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ConditionExpression(
        ConditionExpressionOp op,
        ConditionReference left,
        ConditionExpressionRight right,
        List<Object> values,
        List<ConditionExpression> operands,
        ConditionExpression operand,
        @Wire("const") Boolean constValue
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (op != null) {
            map.put("op", op.wire());
        }
        if (left != null) {
            map.put("left", left.toMap());
        }
        if (right != null) {
            map.put("right", right.toMap());
        }
        if (values != null) {
            map.put("values", values);
        }
        if (operands != null) {
            map.put("operands", operands.stream().map(ConditionExpression::toMap).toList());
        }
        if (operand != null) {
            map.put("operand", operand.toMap());
        }
        if (constValue != null) {
            map.put("const", constValue);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ConditionExpression fromMap(Map<String, Object> map) {
        return new ConditionExpression(
                map.get("op") == null ? null : ConditionExpressionOp.fromWire((String) map.get("op")),
                map.get("left") == null ? null : ConditionReference.fromMap(asMap(map.get("left"))),
                map.get("right") == null ? null : ConditionExpressionRight.fromMap(asMap(map.get("right"))),
                map.get("values") == null ? null : asList(map.get("values")),
                map.get("operands") == null ? null : asList(map.get("operands")).stream().map(e -> ConditionExpression.fromMap(asMap(e))).toList(),
                map.get("operand") == null ? null : ConditionExpression.fromMap(asMap(map.get("operand"))),
                map.get("const") == null ? null : (Boolean) map.get("const")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
