package io.aiplatform.contracts;

/**
 * Discriminates the branches of the union. The members are the union of the values each branch
 * permits.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/condition.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ConditionExpressionOp {
    EQ("eq"),
    NE("ne"),
    LT("lt"),
    LTE("lte"),
    GT("gt"),
    GTE("gte"),
    IN("in"),
    NOTIN("notIn"),
    EXISTS("exists"),
    NOTEXISTS("notExists"),
    AND("and"),
    OR("or"),
    NOT("not");

    private final String wire;

    ConditionExpressionOp(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ConditionExpressionOp fromWire(String value) {
        for (ConditionExpressionOp candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ConditionExpressionOp value: " + value);
    }
}
