package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Union of mutually exclusive branches; exactly one branch's required fields are present in a
 * valid document, which the JSON Schema enforces and this type does not.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/condition.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ConditionComparisonRight(
        ConditionComparisonRightSource source,
        String nodeId,
        String path,
        Object value
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (source != null) {
            map.put("source", source.wire());
        }
        if (nodeId != null) {
            map.put("nodeId", nodeId);
        }
        if (path != null) {
            map.put("path", path);
        }
        if (value != null) {
            map.put("value", value);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ConditionComparisonRight fromMap(Map<String, Object> map) {
        return new ConditionComparisonRight(
                map.get("source") == null ? null : ConditionComparisonRightSource.fromWire((String) map.get("source")),
                map.get("nodeId") == null ? null : (String) map.get("nodeId"),
                map.get("path") == null ? null : (String) map.get("path"),
                map.get("value") == null ? null : (Object) map.get("value")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
