package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/graph/condition.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ConditionMembershipOp {
    IN("in"),
    NOTIN("notIn");

    private final String wire;

    ConditionMembershipOp(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ConditionMembershipOp fromWire(String value) {
        for (ConditionMembershipOp candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ConditionMembershipOp value: " + value);
    }
}
