package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A path into validated structured node output or into run variables. Nothing else is
 * addressable.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/condition.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ConditionReference(
        @Required ConditionReferenceSource source,
        @Required String path,
        String nodeId
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("source", source.wire());
        map.put("path", path);
        if (nodeId != null) {
            map.put("nodeId", nodeId);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ConditionReference fromMap(Map<String, Object> map) {
        return new ConditionReference(
                ConditionReferenceSource.fromWire((String) map.get("source")),
                (String) map.get("path"),
                map.get("nodeId") == null ? null : (String) map.get("nodeId")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
