package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/graph/condition.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ConditionComparison(
        @Required ConditionComparisonOp op,
        @Required ConditionReference left,
        @Required ConditionComparisonRight right
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("op", op.wire());
        map.put("left", left.toMap());
        map.put("right", right.toMap());
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ConditionComparison fromMap(Map<String, Object> map) {
        return new ConditionComparison(
                ConditionComparisonOp.fromWire((String) map.get("op")),
                ConditionReference.fromMap(asMap(map.get("left"))),
                ConditionComparisonRight.fromMap(asMap(map.get("right")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
