package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/context/context-bundle.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ContextBundleItemStrategy {
    DIRECT("DIRECT"),
    PATH_MATCH("PATH_MATCH"),
    SEARCH("SEARCH"),
    LINK_TRAVERSAL("LINK_TRAVERSAL"),
    GRAPH_STATE("GRAPH_STATE");

    private final String wire;

    ContextBundleItemStrategy(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ContextBundleItemStrategy fromWire(String value) {
        for (ContextBundleItemStrategy candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ContextBundleItemStrategy value: " + value);
    }
}
