package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/context/context-bundle.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ContextBundleItemSourceSystem {
    REPOSITORY("REPOSITORY"),
    JIRA("JIRA"),
    CONFLUENCE("CONFLUENCE"),
    GITHUB("GITHUB"),
    PLATFORM("PLATFORM"),
    RUN_STATE("RUN_STATE");

    private final String wire;

    ContextBundleItemSourceSystem(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ContextBundleItemSourceSystem fromWire(String value) {
        for (ContextBundleItemSourceSystem candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ContextBundleItemSourceSystem value: " + value);
    }
}
