package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Exact revisions the bundle was built from. Pinning is what makes a run reproducible:
 * re-running against a moved branch or an edited page is a different experiment.
 *
 * Generated by .github/scripts/codegen.py from schemas/context/context-bundle.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ContextBundlePins(
        List<ContextBundlePinsRepositoriesItem> repositories,
        List<ContextBundlePinsIssuesItem> issues,
        List<ContextBundlePinsPagesItem> pages
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (repositories != null) {
            map.put("repositories", repositories.stream().map(ContextBundlePinsRepositoriesItem::toMap).toList());
        }
        if (issues != null) {
            map.put("issues", issues.stream().map(ContextBundlePinsIssuesItem::toMap).toList());
        }
        if (pages != null) {
            map.put("pages", pages.stream().map(ContextBundlePinsPagesItem::toMap).toList());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ContextBundlePins fromMap(Map<String, Object> map) {
        return new ContextBundlePins(
                map.get("repositories") == null ? null : asList(map.get("repositories")).stream().map(e -> ContextBundlePinsRepositoriesItem.fromMap(asMap(e))).toList(),
                map.get("issues") == null ? null : asList(map.get("issues")).stream().map(e -> ContextBundlePinsIssuesItem.fromMap(asMap(e))).toList(),
                map.get("pages") == null ? null : asList(map.get("pages")).stream().map(e -> ContextBundlePinsPagesItem.fromMap(asMap(e))).toList()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
