package io.aiplatform.contracts;

/**
 * PLATFORM content is platform-authored. UNTRUSTED is everything retrieved from a repository,
 * issue, page or pull request, and is treated as data that may attempt to influence the model.
 * It is never rendered where the protocol expects platform-controlled fields.
 *
 * Generated by .github/scripts/codegen.py from schemas/context/context-bundle.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ContextBundleItemTrustClass {
    PLATFORM("PLATFORM"),
    UNTRUSTED("UNTRUSTED");

    private final String wire;

    ContextBundleItemTrustClass(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ContextBundleItemTrustClass fromWire(String value) {
        for (ContextBundleItemTrustClass candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ContextBundleItemTrustClass value: " + value);
    }
}
