package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/context/context-bundle.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ContextBundleExcludedItemReason {
    EVICTED_BUDGET("EVICTED_BUDGET"),
    POLICY_EXCLUDED("POLICY_EXCLUDED"),
    ACCESS_DENIED("ACCESS_DENIED"),
    STALE("STALE");

    private final String wire;

    ContextBundleExcludedItemReason(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ContextBundleExcludedItemReason fromWire(String value) {
        for (ContextBundleExcludedItemReason candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ContextBundleExcludedItemReason value: " + value);
    }
}
