package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * An immutable, content-addressed set of retrieved material assembled for one node attempt
 * (ADR-0013). bundleRef is sha256 of the canonical serialisation. The bundle records not only
 * what was included but why, what was excluded and under whose identity each item was
 * retrieved, so the platform can answer 'why did the agent see this?' from durable state.
 *
 * Generated by .github/scripts/codegen.py from schemas/context/context-bundle.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ContextBundle(
        @Required String schemaVersion,
        @Required String bundleRef,
        @Required String runId,
        @Required String nodeId,
        @Required String createdAt,
        @Required ContextBundleBudget budget,
        @Required ContextBundlePins pins,
        @Required List<ContextBundleItem> items,
        @Required List<ContextBundleExcludedItem> excluded,
        String supersedes
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("bundleRef", bundleRef);
        map.put("runId", runId);
        map.put("nodeId", nodeId);
        map.put("createdAt", createdAt);
        map.put("budget", budget.toMap());
        map.put("pins", pins.toMap());
        map.put("items", items.stream().map(ContextBundleItem::toMap).toList());
        map.put("excluded", excluded.stream().map(ContextBundleExcludedItem::toMap).toList());
        if (supersedes != null) {
            map.put("supersedes", supersedes);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ContextBundle fromMap(Map<String, Object> map) {
        return new ContextBundle(
                (String) map.get("schemaVersion"),
                (String) map.get("bundleRef"),
                (String) map.get("runId"),
                (String) map.get("nodeId"),
                (String) map.get("createdAt"),
                ContextBundleBudget.fromMap(asMap(map.get("budget"))),
                ContextBundlePins.fromMap(asMap(map.get("pins"))),
                asList(map.get("items")).stream().map(e -> ContextBundleItem.fromMap(asMap(e))).toList(),
                asList(map.get("excluded")).stream().map(e -> ContextBundleExcludedItem.fromMap(asMap(e))).toList(),
                map.get("supersedes") == null ? null : (String) map.get("supersedes")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
