package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/context/context-bundle.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ContextBundleItem(
        @Required String itemId,
        @Required ContextBundleItemSourceSystem sourceSystem,
        @Required String sourceId,
        @Required String revision,
        @Required String retrievedAt,
        @Required String retrievedAs,
        @Required ContextBundleItemStrategy strategy,
        @Required long tokenCount,
        @Required String inclusionReason,
        @Required ContextBundleItemTrustClass trustClass,
        @Required ArtifactRef contentRef,
        Long relevanceScore
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("itemId", itemId);
        map.put("sourceSystem", sourceSystem.wire());
        map.put("sourceId", sourceId);
        map.put("revision", revision);
        map.put("retrievedAt", retrievedAt);
        map.put("retrievedAs", retrievedAs);
        map.put("strategy", strategy.wire());
        map.put("tokenCount", tokenCount);
        map.put("inclusionReason", inclusionReason);
        map.put("trustClass", trustClass.wire());
        map.put("contentRef", contentRef.toMap());
        if (relevanceScore != null) {
            map.put("relevanceScore", relevanceScore);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ContextBundleItem fromMap(Map<String, Object> map) {
        return new ContextBundleItem(
                (String) map.get("itemId"),
                ContextBundleItemSourceSystem.fromWire((String) map.get("sourceSystem")),
                (String) map.get("sourceId"),
                (String) map.get("revision"),
                (String) map.get("retrievedAt"),
                (String) map.get("retrievedAs"),
                ContextBundleItemStrategy.fromWire((String) map.get("strategy")),
                ((Number) map.get("tokenCount")).longValue(),
                (String) map.get("inclusionReason"),
                ContextBundleItemTrustClass.fromWire((String) map.get("trustClass")),
                ArtifactRef.fromMap(asMap(map.get("contentRef"))),
                map.get("relevanceScore") == null ? null : ((Number) map.get("relevanceScore")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
