package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Telemetry correlation block. ADR-0003 §4: carried, never interpreted. ADR-0015 §7: these
 * values are forbidden as metric labels. Carries the full four-part NodeRun key (ADR-0021 §6)
 * so a log line, a span and a stored record name the same thing.
 *
 * Generated by .github/scripts/codegen.py from schemas/common/common.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record Correlation(
        @Required String runId,
        @Required String nodeId,
        @Required long iteration,
        @Required long attempt,
        String agentId,
        String traceparent
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("runId", runId);
        map.put("nodeId", nodeId);
        map.put("iteration", iteration);
        map.put("attempt", attempt);
        if (agentId != null) {
            map.put("agentId", agentId);
        }
        if (traceparent != null) {
            map.put("traceparent", traceparent);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static Correlation fromMap(Map<String, Object> map) {
        return new Correlation(
                (String) map.get("runId"),
                (String) map.get("nodeId"),
                ((Number) map.get("iteration")).longValue(),
                ((Number) map.get("attempt")).longValue(),
                map.get("agentId") == null ? null : (String) map.get("agentId"),
                map.get("traceparent") == null ? null : (String) map.get("traceparent")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
