package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/execution/execution-result.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ExecutionResultStatus {
    COMPLETED("COMPLETED"),
    TIMED_OUT("TIMED_OUT"),
    CANCELLED("CANCELLED"),
    RESOURCE_EXCEEDED("RESOURCE_EXCEEDED"),
    EXECUTOR_ERROR("EXECUTOR_ERROR");

    private final String wire;

    ExecutionResultStatus(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ExecutionResultStatus fromWire(String value) {
        for (ExecutionResultStatus candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ExecutionResultStatus value: " + value);
    }
}
