package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Returned by await() or poll() (ADR-0003 §4). A non-zero exit code is a result, not an error:
 * a failing test is the normal case in a repair loop. The error taxonomy is reserved for the
 * executor failing to run the command at all.
 *
 * Generated by .github/scripts/codegen.py from schemas/execution/execution-result.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ExecutionResult(
        @Required String protocolVersion,
        @Required ExecutionResultStatus status,
        @Required ArtifactRef stdoutRef,
        @Required ArtifactRef stderrRef,
        @Required long durationMs,
        @Required List<ExecutionResultNetworkDenialsItem> networkDenials,
        Long exitCode,
        String stdoutPreview,
        String stderrPreview,
        ResourceUsage resourceUsage
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("protocolVersion", protocolVersion);
        map.put("status", status.wire());
        map.put("stdoutRef", stdoutRef.toMap());
        map.put("stderrRef", stderrRef.toMap());
        map.put("durationMs", durationMs);
        map.put("networkDenials", networkDenials.stream().map(ExecutionResultNetworkDenialsItem::toMap).toList());
        if (exitCode != null) {
            map.put("exitCode", exitCode);
        }
        if (stdoutPreview != null) {
            map.put("stdoutPreview", stdoutPreview);
        }
        if (stderrPreview != null) {
            map.put("stderrPreview", stderrPreview);
        }
        if (resourceUsage != null) {
            map.put("resourceUsage", resourceUsage.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ExecutionResult fromMap(Map<String, Object> map) {
        return new ExecutionResult(
                (String) map.get("protocolVersion"),
                ExecutionResultStatus.fromWire((String) map.get("status")),
                ArtifactRef.fromMap(asMap(map.get("stdoutRef"))),
                ArtifactRef.fromMap(asMap(map.get("stderrRef"))),
                ((Number) map.get("durationMs")).longValue(),
                asList(map.get("networkDenials")).stream().map(e -> ExecutionResultNetworkDenialsItem.fromMap(asMap(e))).toList(),
                map.get("exitCode") == null ? null : ((Number) map.get("exitCode")).longValue(),
                map.get("stdoutPreview") == null ? null : (String) map.get("stdoutPreview"),
                map.get("stderrPreview") == null ? null : (String) map.get("stderrPreview"),
                map.get("resourceUsage") == null ? null : ResourceUsage.fromMap(asMap(map.get("resourceUsage")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
