package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Submitted to the execution interface (ADR-0003 §4). The shape encodes the six
 * substitutability rules of ADR-0003 §3: argv arrays rather than shell strings, an explicit
 * environment allowlist rather than inheritance, artifact references rather than paths, and
 * mandatory timeout, limits and network policy.
 *
 * Generated by .github/scripts/codegen.py from schemas/execution/execution-request.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ExecutionRequest(
        @Required String protocolVersion,
        @Required List<String> argv,
        @Required String cwd,
        @Required Map<String, String> envAllowlist,
        @Required long timeoutMs,
        @Required ResourceLimits resourceLimits,
        @Required NetworkPolicy networkPolicy,
        @Required Correlation correlation,
        ArtifactRef stdinRef
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("protocolVersion", protocolVersion);
        map.put("argv", argv);
        map.put("cwd", cwd);
        map.put("envAllowlist", envAllowlist);
        map.put("timeoutMs", timeoutMs);
        map.put("resourceLimits", resourceLimits.toMap());
        map.put("networkPolicy", networkPolicy.toMap());
        map.put("correlation", correlation.toMap());
        if (stdinRef != null) {
            map.put("stdinRef", stdinRef.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ExecutionRequest fromMap(Map<String, Object> map) {
        return new ExecutionRequest(
                (String) map.get("protocolVersion"),
                asList(map.get("argv")),
                (String) map.get("cwd"),
                asMap(map.get("envAllowlist")),
                ((Number) map.get("timeoutMs")).longValue(),
                ResourceLimits.fromMap(asMap(map.get("resourceLimits"))),
                NetworkPolicy.fromMap(asMap(map.get("networkPolicy"))),
                Correlation.fromMap(asMap(map.get("correlation"))),
                map.get("stdinRef") == null ? null : ArtifactRef.fromMap(asMap(map.get("stdinRef")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
