package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/execution/execution-result.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ExecutionResultNetworkDenialsItem(
        @Required String host,
        @Required long count,
        Long port,
        String firstSeenAt
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("host", host);
        map.put("count", count);
        if (port != null) {
            map.put("port", port);
        }
        if (firstSeenAt != null) {
            map.put("firstSeenAt", firstSeenAt);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ExecutionResultNetworkDenialsItem fromMap(Map<String, Object> map) {
        return new ExecutionResultNetworkDenialsItem(
                (String) map.get("host"),
                ((Number) map.get("count")).longValue(),
                map.get("port") == null ? null : ((Number) map.get("port")).longValue(),
                map.get("firstSeenAt") == null ? null : (String) map.get("firstSeenAt")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
