package io.aiplatform.contracts;

/**
 * ADR-0008 §11, extended by ADR-0009. Retry is driven by category, never by message text.
 *
 * Generated by .github/scripts/codegen.py from schemas/common/common.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum FailureCategory {
    TRANSIENT("TRANSIENT"),
    MODEL_ERROR("MODEL_ERROR"),
    BUDGET_EXCEEDED("BUDGET_EXCEEDED"),
    INVALID_OUTPUT("INVALID_OUTPUT"),
    TOOL_DENIED("TOOL_DENIED"),
    VERIFICATION_FAILED("VERIFICATION_FAILED"),
    EXECUTION_ERROR("EXECUTION_ERROR"),
    INTEGRATION_ERROR("INTEGRATION_ERROR"),
    INDETERMINATE("INDETERMINATE"),
    CANCELLED("CANCELLED"),
    APPROVAL_REJECTED("APPROVAL_REJECTED"),
    APPROVAL_EXPIRED("APPROVAL_EXPIRED"),
    DEFINITION_UNAVAILABLE("DEFINITION_UNAVAILABLE");

    private final String wire;

    FailureCategory(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static FailureCategory fromWire(String value) {
        for (FailureCategory candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown FailureCategory value: " + value);
    }
}
