package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * ADR-0026 §3. The run ceiling, and the only budget that is mandatory. Node and grant budgets
 * are optional and are clamped to what remains here, so the nesting is genuine containment
 * rather than four independent numbers.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/graph-run.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record GraphRunBudget(
        @Required long maxCostUnits,
        Long maxDurationMs
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("maxCostUnits", maxCostUnits);
        if (maxDurationMs != null) {
            map.put("maxDurationMs", maxDurationMs);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static GraphRunBudget fromMap(Map<String, Object> map) {
        return new GraphRunBudget(
                ((Number) map.get("maxCostUnits")).longValue(),
                map.get("maxDurationMs") == null ? null : ((Number) map.get("maxDurationMs")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
