package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/graph/graph.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record GraphAgentNode(
        @Required String id,
        @Required String type,
        @Required String agentId,
        @Required String objective,
        @Required Map<String, Object> outputSchema,
        @Required GraphAgentNodeRequestedCapabilities requestedCapabilities,
        @Required GraphAgentNodeBudgets budgets,
        String title,
        Long timeoutMs,
        GraphRetryPolicy retryPolicy,
        GraphAgentNodeModelPolicy modelPolicy
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("id", id);
        map.put("type", type);
        map.put("agentId", agentId);
        map.put("objective", objective);
        map.put("outputSchema", outputSchema);
        map.put("requestedCapabilities", requestedCapabilities.toMap());
        map.put("budgets", budgets.toMap());
        if (title != null) {
            map.put("title", title);
        }
        if (timeoutMs != null) {
            map.put("timeoutMs", timeoutMs);
        }
        if (retryPolicy != null) {
            map.put("retryPolicy", retryPolicy.toMap());
        }
        if (modelPolicy != null) {
            map.put("modelPolicy", modelPolicy.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static GraphAgentNode fromMap(Map<String, Object> map) {
        return new GraphAgentNode(
                (String) map.get("id"),
                (String) map.get("type"),
                (String) map.get("agentId"),
                (String) map.get("objective"),
                (Map<String, Object>) map.get("outputSchema"),
                GraphAgentNodeRequestedCapabilities.fromMap(asMap(map.get("requestedCapabilities"))),
                GraphAgentNodeBudgets.fromMap(asMap(map.get("budgets"))),
                map.get("title") == null ? null : (String) map.get("title"),
                map.get("timeoutMs") == null ? null : ((Number) map.get("timeoutMs")).longValue(),
                map.get("retryPolicy") == null ? null : GraphRetryPolicy.fromMap(asMap(map.get("retryPolicy"))),
                map.get("modelPolicy") == null ? null : GraphAgentNodeModelPolicy.fromMap(asMap(map.get("modelPolicy")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
