package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/graph/graph.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record GraphRetryPolicyBackoff(
        @Required GraphRetryPolicyBackoffStrategy strategy,
        @Required long initialDelayMs,
        Long maxDelayMs,
        Boolean jitter
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("strategy", strategy.wire());
        map.put("initialDelayMs", initialDelayMs);
        if (maxDelayMs != null) {
            map.put("maxDelayMs", maxDelayMs);
        }
        if (jitter != null) {
            map.put("jitter", jitter);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static GraphRetryPolicyBackoff fromMap(Map<String, Object> map) {
        return new GraphRetryPolicyBackoff(
                GraphRetryPolicyBackoffStrategy.fromWire((String) map.get("strategy")),
                ((Number) map.get("initialDelayMs")).longValue(),
                map.get("maxDelayMs") == null ? null : ((Number) map.get("maxDelayMs")).longValue(),
                map.get("jitter") == null ? null : (Boolean) map.get("jitter")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
