package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * ADR-0008 §8: exactly one orchestrator per run. This is a security control as well as a
 * correctness one, because two orchestrators would produce duplicate external side effects.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/graph-run.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record GraphRunLease(
        @Required String holderId,
        @Required String acquiredAt,
        @Required String expiresAt
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("holderId", holderId);
        map.put("acquiredAt", acquiredAt);
        map.put("expiresAt", expiresAt);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static GraphRunLease fromMap(Map<String, Object> map) {
        return new GraphRunLease(
                (String) map.get("holderId"),
                (String) map.get("acquiredAt"),
                (String) map.get("expiresAt")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
