package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A durable pause (ADR-0008 §13). The engine writes AWAITING_APPROVAL, releases the lease and
 * stops; nothing is held in memory.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/graph.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record GraphApprovalNode(
        @Required String id,
        @Required String type,
        @Required GraphApprovalNodeRequiredKind requiredKind,
        @Required String subjectRef,
        @Required long expiresAfterMs,
        String title
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("id", id);
        map.put("type", type);
        map.put("requiredKind", requiredKind.wire());
        map.put("subjectRef", subjectRef);
        map.put("expiresAfterMs", expiresAfterMs);
        if (title != null) {
            map.put("title", title);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static GraphApprovalNode fromMap(Map<String, Object> map) {
        return new GraphApprovalNode(
                (String) map.get("id"),
                (String) map.get("type"),
                GraphApprovalNodeRequiredKind.fromWire((String) map.get("requiredKind")),
                (String) map.get("subjectRef"),
                ((Number) map.get("expiresAfterMs")).longValue(),
                map.get("title") == null ? null : (String) map.get("title")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
