package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The Jira issue this run serves, where there is one. Jira remains the system of record; this
 * is a reference, not a copy.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/graph-run.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record GraphRunWorkItemRef(
        @Required String system,
        @Required String key
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("system", system);
        map.put("key", key);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static GraphRunWorkItemRef fromMap(Map<String, Object> map) {
        return new GraphRunWorkItemRef(
                (String) map.get("system"),
                (String) map.get("key")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
