package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A deterministic side effect. Exactly one tool, fixed in the definition. This is the escape
 * hatch for behaviour the condition language cannot express (ADR-0008 Consequences).
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/graph.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record GraphToolNode(
        @Required String id,
        @Required String type,
        @Required String toolId,
        @Required String toolVersion,
        @Required Map<String, Object> input,
        String title,
        Long timeoutMs,
        GraphRetryPolicy retryPolicy
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("id", id);
        map.put("type", type);
        map.put("toolId", toolId);
        map.put("toolVersion", toolVersion);
        map.put("input", input);
        if (title != null) {
            map.put("title", title);
        }
        if (timeoutMs != null) {
            map.put("timeoutMs", timeoutMs);
        }
        if (retryPolicy != null) {
            map.put("retryPolicy", retryPolicy.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static GraphToolNode fromMap(Map<String, Object> map) {
        return new GraphToolNode(
                (String) map.get("id"),
                (String) map.get("type"),
                (String) map.get("toolId"),
                (String) map.get("toolVersion"),
                (Map<String, Object>) map.get("input"),
                map.get("title") == null ? null : (String) map.get("title"),
                map.get("timeoutMs") == null ? null : ((Number) map.get("timeoutMs")).longValue(),
                map.get("retryPolicy") == null ? null : GraphRetryPolicy.fromMap(asMap(map.get("retryPolicy")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
