package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A workflow, expressed as declarative data (ADR-0008 §1). Contains no code and no expressions
 * beyond the restricted condition language. Definitions are immutable and content-addressed:
 * editing produces a new version identified by the content hash of its canonical form, and a
 * run pins the version it started with for its entire life. ADR-0008 §16: graphs are authored
 * by humans. An agent may propose a definition as a reviewable artifact, but no agent may
 * author, mutate or select a definition for a live run.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/graph.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record Graph(
        @Required String schemaVersion,
        @Required String graphId,
        @Required String title,
        @Required String entryNodeId,
        @Required List<GraphNode> nodes,
        @Required List<GraphEdge> edges,
        String description,
        Map<String, Map<String, Object>> variables,
        GraphRetryPolicy defaultRetryPolicy
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("graphId", graphId);
        map.put("title", title);
        map.put("entryNodeId", entryNodeId);
        map.put("nodes", nodes.stream().map(GraphNode::toMap).toList());
        map.put("edges", edges.stream().map(GraphEdge::toMap).toList());
        if (description != null) {
            map.put("description", description);
        }
        if (variables != null) {
            map.put("variables", variables);
        }
        if (defaultRetryPolicy != null) {
            map.put("defaultRetryPolicy", defaultRetryPolicy.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static Graph fromMap(Map<String, Object> map) {
        return new Graph(
                (String) map.get("schemaVersion"),
                (String) map.get("graphId"),
                (String) map.get("title"),
                (String) map.get("entryNodeId"),
                asList(map.get("nodes")).stream().map(e -> GraphNode.fromMap(asMap(e))).toList(),
                asList(map.get("edges")).stream().map(e -> GraphEdge.fromMap(asMap(e))).toList(),
                map.get("description") == null ? null : (String) map.get("description"),
                map.get("variables") == null ? null : asMap(map.get("variables")),
                map.get("defaultRetryPolicy") == null ? null : GraphRetryPolicy.fromMap(asMap(map.get("defaultRetryPolicy")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
