package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/graph/graph.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum GraphRetryPolicyBackoffStrategy {
    FIXED("FIXED"),
    EXPONENTIAL("EXPONENTIAL");

    private final String wire;

    GraphRetryPolicyBackoffStrategy(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static GraphRetryPolicyBackoffStrategy fromWire(String value) {
        for (GraphRetryPolicyBackoffStrategy candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown GraphRetryPolicyBackoffStrategy value: " + value);
    }
}
