package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/graph/graph.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum GraphRetryPolicyRetryableCategoriesItem {
    TRANSIENT("TRANSIENT"),
    MODEL_ERROR("MODEL_ERROR"),
    BUDGET_EXCEEDED("BUDGET_EXCEEDED"),
    INVALID_OUTPUT("INVALID_OUTPUT"),
    TOOL_DENIED("TOOL_DENIED"),
    VERIFICATION_FAILED("VERIFICATION_FAILED"),
    EXECUTION_ERROR("EXECUTION_ERROR"),
    INTEGRATION_ERROR("INTEGRATION_ERROR");

    private final String wire;

    GraphRetryPolicyRetryableCategoriesItem(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static GraphRetryPolicyRetryableCategoriesItem fromWire(String value) {
        for (GraphRetryPolicyRetryableCategoriesItem candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown GraphRetryPolicyRetryableCategoriesItem value: " + value);
    }
}
