package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * ADR-0008 §11. Policy lives in the definition and is therefore versioned and pinned; retry
 * state lives on the node. Retry is driven by category, never by message text.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/graph.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record GraphRetryPolicy(
        @Required long maxAttempts,
        @Required GraphRetryPolicyBackoff backoff,
        @Required List<GraphRetryPolicyRetryableCategoriesItem> retryableCategories
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("maxAttempts", maxAttempts);
        map.put("backoff", backoff.toMap());
        map.put("retryableCategories", retryableCategories.stream().map(GraphRetryPolicyRetryableCategoriesItem::wire).toList());
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static GraphRetryPolicy fromMap(Map<String, Object> map) {
        return new GraphRetryPolicy(
                ((Number) map.get("maxAttempts")).longValue(),
                GraphRetryPolicyBackoff.fromMap(asMap(map.get("backoff"))),
                asList(map.get("retryableCategories")).stream().map(e -> GraphRetryPolicyRetryableCategoriesItem.fromWire((String) e)).toList()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
