package io.aiplatform.contracts;

/**
 * ADR-0008 §6. SUSPENDED is the normal consequence of closing a laptop — an expected,
 * recoverable state, not a failure. Terminal states are immutable.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/graph-run.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum GraphRunStatus {
    PENDING("PENDING"),
    RUNNING("RUNNING"),
    AWAITING_APPROVAL("AWAITING_APPROVAL"),
    AWAITING_RETRY("AWAITING_RETRY"),
    SUSPENDED("SUSPENDED"),
    SUCCEEDED("SUCCEEDED"),
    FAILED("FAILED"),
    CANCELLED("CANCELLED"),
    TIMED_OUT("TIMED_OUT");

    private final String wire;

    GraphRunStatus(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static GraphRunStatus fromWire(String value) {
        for (GraphRunStatus candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown GraphRunStatus value: " + value);
    }
}
