package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * ADR-0008 §3 defines a closed node taxonomy. Adding a node type requires an ADR, so this list
 * is intentionally exhaustive. Union of mutually exclusive branches; exactly one branch's
 * required fields are present in a valid document, which the JSON Schema enforces and this
 * type does not.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/graph.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record GraphNode(
        String id,
        GraphNodeType type,
        String title,
        Long timeoutMs,
        GraphRetryPolicy retryPolicy,
        String contextPolicyId,
        Long tokenBudget,
        String agentId,
        String objective,
        Map<String, Object> outputSchema,
        GraphNodeRequestedCapabilities requestedCapabilities,
        GraphNodeBudgets budgets,
        GraphNodeModelPolicy modelPolicy,
        String toolId,
        String toolVersion,
        Map<String, Object> input,
        GraphNodeRequiredKind requiredKind,
        String subjectRef,
        Long expiresAfterMs,
        String bodyNodeId,
        Long maxIterations,
        ConditionExpression exitCondition,
        GraphNodeOutcome outcome
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (id != null) {
            map.put("id", id);
        }
        if (type != null) {
            map.put("type", type.wire());
        }
        if (title != null) {
            map.put("title", title);
        }
        if (timeoutMs != null) {
            map.put("timeoutMs", timeoutMs);
        }
        if (retryPolicy != null) {
            map.put("retryPolicy", retryPolicy.toMap());
        }
        if (contextPolicyId != null) {
            map.put("contextPolicyId", contextPolicyId);
        }
        if (tokenBudget != null) {
            map.put("tokenBudget", tokenBudget);
        }
        if (agentId != null) {
            map.put("agentId", agentId);
        }
        if (objective != null) {
            map.put("objective", objective);
        }
        if (outputSchema != null) {
            map.put("outputSchema", outputSchema);
        }
        if (requestedCapabilities != null) {
            map.put("requestedCapabilities", requestedCapabilities.toMap());
        }
        if (budgets != null) {
            map.put("budgets", budgets.toMap());
        }
        if (modelPolicy != null) {
            map.put("modelPolicy", modelPolicy.toMap());
        }
        if (toolId != null) {
            map.put("toolId", toolId);
        }
        if (toolVersion != null) {
            map.put("toolVersion", toolVersion);
        }
        if (input != null) {
            map.put("input", input);
        }
        if (requiredKind != null) {
            map.put("requiredKind", requiredKind.wire());
        }
        if (subjectRef != null) {
            map.put("subjectRef", subjectRef);
        }
        if (expiresAfterMs != null) {
            map.put("expiresAfterMs", expiresAfterMs);
        }
        if (bodyNodeId != null) {
            map.put("bodyNodeId", bodyNodeId);
        }
        if (maxIterations != null) {
            map.put("maxIterations", maxIterations);
        }
        if (exitCondition != null) {
            map.put("exitCondition", exitCondition.toMap());
        }
        if (outcome != null) {
            map.put("outcome", outcome.wire());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static GraphNode fromMap(Map<String, Object> map) {
        return new GraphNode(
                map.get("id") == null ? null : (String) map.get("id"),
                map.get("type") == null ? null : GraphNodeType.fromWire((String) map.get("type")),
                map.get("title") == null ? null : (String) map.get("title"),
                map.get("timeoutMs") == null ? null : ((Number) map.get("timeoutMs")).longValue(),
                map.get("retryPolicy") == null ? null : GraphRetryPolicy.fromMap(asMap(map.get("retryPolicy"))),
                map.get("contextPolicyId") == null ? null : (String) map.get("contextPolicyId"),
                map.get("tokenBudget") == null ? null : ((Number) map.get("tokenBudget")).longValue(),
                map.get("agentId") == null ? null : (String) map.get("agentId"),
                map.get("objective") == null ? null : (String) map.get("objective"),
                map.get("outputSchema") == null ? null : (Map<String, Object>) map.get("outputSchema"),
                map.get("requestedCapabilities") == null ? null : GraphNodeRequestedCapabilities.fromMap(asMap(map.get("requestedCapabilities"))),
                map.get("budgets") == null ? null : GraphNodeBudgets.fromMap(asMap(map.get("budgets"))),
                map.get("modelPolicy") == null ? null : GraphNodeModelPolicy.fromMap(asMap(map.get("modelPolicy"))),
                map.get("toolId") == null ? null : (String) map.get("toolId"),
                map.get("toolVersion") == null ? null : (String) map.get("toolVersion"),
                map.get("input") == null ? null : (Map<String, Object>) map.get("input"),
                map.get("requiredKind") == null ? null : GraphNodeRequiredKind.fromWire((String) map.get("requiredKind")),
                map.get("subjectRef") == null ? null : (String) map.get("subjectRef"),
                map.get("expiresAfterMs") == null ? null : ((Number) map.get("expiresAfterMs")).longValue(),
                map.get("bodyNodeId") == null ? null : (String) map.get("bodyNodeId"),
                map.get("maxIterations") == null ? null : ((Number) map.get("maxIterations")).longValue(),
                map.get("exitCondition") == null ? null : ConditionExpression.fromMap(asMap(map.get("exitCondition"))),
                map.get("outcome") == null ? null : GraphNodeOutcome.fromWire((String) map.get("outcome"))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
