package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The durable record of a graph run (ADR-0008). This is the authoritative state: the HTTP call
 * that dispatches a node attempt is an optimisation, not the record (ADR-0004 §7). Only the
 * holder of the lease may transition a run.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/graph-run.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record GraphRun(
        @Required String schemaVersion,
        @Required String runId,
        @Required long version,
        @Required String graphId,
        @Required String graphVersionHash,
        @Required GraphRunStatus status,
        @Required long epoch,
        @Required List<String> repositories,
        @Required boolean cancellationRequested,
        @Required String currency,
        @Required GraphRunBudget budget,
        @Required long consumedCostUnits,
        @Required String initiatedBy,
        @Required String createdAt,
        @Required String updatedAt,
        Map<String, String> agentPins,
        GraphRunLease lease,
        GraphRunWorkItemRef workItemRef,
        String workspaceId,
        Map<String, Object> variables,
        String approvalDeadline,
        String currentNodeId,
        String latestCheckpointId,
        String completedAt,
        GraphRunFailure failure
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("runId", runId);
        map.put("version", version);
        map.put("graphId", graphId);
        map.put("graphVersionHash", graphVersionHash);
        map.put("status", status.wire());
        map.put("epoch", epoch);
        map.put("repositories", repositories);
        map.put("cancellationRequested", cancellationRequested);
        map.put("currency", currency);
        map.put("budget", budget.toMap());
        map.put("consumedCostUnits", consumedCostUnits);
        map.put("initiatedBy", initiatedBy);
        map.put("createdAt", createdAt);
        map.put("updatedAt", updatedAt);
        if (agentPins != null) {
            map.put("agentPins", agentPins);
        }
        if (lease != null) {
            map.put("lease", lease.toMap());
        }
        if (workItemRef != null) {
            map.put("workItemRef", workItemRef.toMap());
        }
        if (workspaceId != null) {
            map.put("workspaceId", workspaceId);
        }
        if (variables != null) {
            map.put("variables", variables);
        }
        if (approvalDeadline != null) {
            map.put("approvalDeadline", approvalDeadline);
        }
        if (currentNodeId != null) {
            map.put("currentNodeId", currentNodeId);
        }
        if (latestCheckpointId != null) {
            map.put("latestCheckpointId", latestCheckpointId);
        }
        if (completedAt != null) {
            map.put("completedAt", completedAt);
        }
        if (failure != null) {
            map.put("failure", failure.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static GraphRun fromMap(Map<String, Object> map) {
        return new GraphRun(
                (String) map.get("schemaVersion"),
                (String) map.get("runId"),
                ((Number) map.get("version")).longValue(),
                (String) map.get("graphId"),
                (String) map.get("graphVersionHash"),
                GraphRunStatus.fromWire((String) map.get("status")),
                ((Number) map.get("epoch")).longValue(),
                asList(map.get("repositories")),
                (Boolean) map.get("cancellationRequested"),
                (String) map.get("currency"),
                GraphRunBudget.fromMap(asMap(map.get("budget"))),
                ((Number) map.get("consumedCostUnits")).longValue(),
                (String) map.get("initiatedBy"),
                (String) map.get("createdAt"),
                (String) map.get("updatedAt"),
                map.get("agentPins") == null ? null : asMap(map.get("agentPins")),
                map.get("lease") == null ? null : GraphRunLease.fromMap(asMap(map.get("lease"))),
                map.get("workItemRef") == null ? null : GraphRunWorkItemRef.fromMap(asMap(map.get("workItemRef"))),
                map.get("workspaceId") == null ? null : (String) map.get("workspaceId"),
                map.get("variables") == null ? null : (Map<String, Object>) map.get("variables"),
                map.get("approvalDeadline") == null ? null : (String) map.get("approvalDeadline"),
                map.get("currentNodeId") == null ? null : (String) map.get("currentNodeId"),
                map.get("latestCheckpointId") == null ? null : (String) map.get("latestCheckpointId"),
                map.get("completedAt") == null ? null : (String) map.get("completedAt"),
                map.get("failure") == null ? null : GraphRunFailure.fromMap(asMap(map.get("failure")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
