package io.aiplatform.contracts;

/**
 * ADR-0010 §6. CONTENT_FILTER is recorded and never silently swallowed.
 *
 * Generated by .github/scripts/codegen.py from schemas/model/model-response.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ModelResponseErrorCategory {
    RATE_LIMITED("RATE_LIMITED"),
    TRANSIENT("TRANSIENT"),
    TIMEOUT("TIMEOUT"),
    AUTH("AUTH"),
    INVALID_REQUEST("INVALID_REQUEST"),
    CONTEXT_TOO_LARGE("CONTEXT_TOO_LARGE"),
    CONTENT_FILTER("CONTENT_FILTER"),
    INVALID_OUTPUT("INVALID_OUTPUT"),
    PROVIDER_ERROR("PROVIDER_ERROR");

    private final String wire;

    ModelResponseErrorCategory(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ModelResponseErrorCategory fromWire(String value) {
        for (ModelResponseErrorCategory candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ModelResponseErrorCategory value: " + value);
    }
}
