package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Union of mutually exclusive branches; exactly one branch's required fields are present in a
 * valid document, which the JSON Schema enforces and this type does not.
 *
 * Generated by .github/scripts/codegen.py from schemas/model/model-response.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ModelResponseContentItem(
        ModelResponseContentItemType type,
        String text,
        String toolCallId
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (type != null) {
            map.put("type", type.wire());
        }
        if (text != null) {
            map.put("text", text);
        }
        if (toolCallId != null) {
            map.put("toolCallId", toolCallId);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ModelResponseContentItem fromMap(Map<String, Object> map) {
        return new ModelResponseContentItem(
                map.get("type") == null ? null : ModelResponseContentItemType.fromWire((String) map.get("type")),
                map.get("text") == null ? null : (String) map.get("text"),
                map.get("toolCallId") == null ? null : (String) map.get("toolCallId")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
