package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/model/model-response.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ModelResponseToolCallsItem(
        @Required String toolCallId,
        @Required String name,
        @Required Map<String, Object> arguments
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("toolCallId", toolCallId);
        map.put("name", name);
        map.put("arguments", arguments);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ModelResponseToolCallsItem fromMap(Map<String, Object> map) {
        return new ModelResponseToolCallsItem(
                (String) map.get("toolCallId"),
                (String) map.get("name"),
                (Map<String, Object>) map.get("arguments")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
