package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The provider-neutral request accepted by the model gateway (ADR-0010 §1). Provider-specific
 * SDK calls live behind the gateway and nowhere else. ADR-0010 §2: the gateway does not run
 * the tool-calling loop — it normalises tool calls into requests, and the tool layer decides
 * and executes. Most agent frameworks do run the loop in this position, so this is the default
 * to resist.
 *
 * Generated by .github/scripts/codegen.py from schemas/model/model-request.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ModelRequest(
        @Required String protocolVersion,
        @Required String modelRef,
        @Required List<String> system,
        @Required List<ModelRequestMessagesItem> messages,
        @Required ModelRequestBudgets budgets,
        @Required Correlation correlation,
        List<ModelRequestToolsItem> tools,
        Object toolChoice,
        Map<String, Object> outputContract,
        ModelRequestParams params,
        ModelRequestProviderOptions providerOptions
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("protocolVersion", protocolVersion);
        map.put("modelRef", modelRef);
        map.put("system", system);
        map.put("messages", messages.stream().map(ModelRequestMessagesItem::toMap).toList());
        map.put("budgets", budgets.toMap());
        map.put("correlation", correlation.toMap());
        if (tools != null) {
            map.put("tools", tools.stream().map(ModelRequestToolsItem::toMap).toList());
        }
        if (toolChoice != null) {
            map.put("toolChoice", toolChoice);
        }
        if (outputContract != null) {
            map.put("outputContract", outputContract);
        }
        if (params != null) {
            map.put("params", params.toMap());
        }
        if (providerOptions != null) {
            map.put("providerOptions", providerOptions.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ModelRequest fromMap(Map<String, Object> map) {
        return new ModelRequest(
                (String) map.get("protocolVersion"),
                (String) map.get("modelRef"),
                asList(map.get("system")),
                asList(map.get("messages")).stream().map(e -> ModelRequestMessagesItem.fromMap(asMap(e))).toList(),
                ModelRequestBudgets.fromMap(asMap(map.get("budgets"))),
                Correlation.fromMap(asMap(map.get("correlation"))),
                map.get("tools") == null ? null : asList(map.get("tools")).stream().map(e -> ModelRequestToolsItem.fromMap(asMap(e))).toList(),
                map.get("toolChoice") == null ? null : (Object) map.get("toolChoice"),
                map.get("outputContract") == null ? null : (Map<String, Object>) map.get("outputContract"),
                map.get("params") == null ? null : ModelRequestParams.fromMap(asMap(map.get("params"))),
                map.get("providerOptions") == null ? null : ModelRequestProviderOptions.fromMap(asMap(map.get("providerOptions")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
