package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Computed by the gateway from recorded usage (ADR-0011 §5), never reported by the caller.
 *
 * Generated by .github/scripts/codegen.py from schemas/model/model-response.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ModelResponseCost(
        @Required double amount,
        @Required String currency,
        @Required boolean estimated
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("amount", amount);
        map.put("currency", currency);
        map.put("estimated", estimated);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ModelResponseCost fromMap(Map<String, Object> map) {
        return new ModelResponseCost(
                ((Number) map.get("amount")).doubleValue(),
                (String) map.get("currency"),
                (Boolean) map.get("estimated")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
