package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/model/model-response.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ModelResponseFinishReason {
    STOP("STOP"),
    TOOL_CALLS("TOOL_CALLS"),
    MAX_TOKENS("MAX_TOKENS"),
    CONTENT_FILTER("CONTENT_FILTER"),
    ERROR("ERROR");

    private final String wire;

    ModelResponseFinishReason(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ModelResponseFinishReason fromWire(String value) {
        for (ModelResponseFinishReason candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ModelResponseFinishReason value: " + value);
    }
}
