package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/model/model-request.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ModelRequestMessagesItem(
        @Required ModelRequestMessagesItemRole role,
        @Required List<ModelRequestContentBlock> content,
        String toolCallId
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("role", role.wire());
        map.put("content", content.stream().map(ModelRequestContentBlock::toMap).toList());
        if (toolCallId != null) {
            map.put("toolCallId", toolCallId);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ModelRequestMessagesItem fromMap(Map<String, Object> map) {
        return new ModelRequestMessagesItem(
                ModelRequestMessagesItemRole.fromWire((String) map.get("role")),
                asList(map.get("content")).stream().map(e -> ModelRequestContentBlock.fromMap(asMap(e))).toList(),
                map.get("toolCallId") == null ? null : (String) map.get("toolCallId")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
