package io.aiplatform.contracts;

/**
 * Discriminates the branches of the union. The members are the union of the values each branch
 * permits.
 *
 * Generated by .github/scripts/codegen.py from schemas/model/model-request.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ModelRequestContentBlockType {
    TEXT("TEXT"),
    ARTIFACT("ARTIFACT"),
    TOOL_CALL("TOOL_CALL");

    private final String wire;

    ModelRequestContentBlockType(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ModelRequestContentBlockType fromWire(String value) {
        for (ModelRequestContentBlockType candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ModelRequestContentBlockType value: " + value);
    }
}
