package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/model/model-response.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ModelResponseUsage(
        @Required long inputTokens,
        @Required long outputTokens,
        Long cachedInputTokens,
        Long reasoningTokens
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("inputTokens", inputTokens);
        map.put("outputTokens", outputTokens);
        if (cachedInputTokens != null) {
            map.put("cachedInputTokens", cachedInputTokens);
        }
        if (reasoningTokens != null) {
            map.put("reasoningTokens", reasoningTokens);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ModelResponseUsage fromMap(Map<String, Object> map) {
        return new ModelResponseUsage(
                ((Number) map.get("inputTokens")).longValue(),
                ((Number) map.get("outputTokens")).longValue(),
                map.get("cachedInputTokens") == null ? null : ((Number) map.get("cachedInputTokens")).longValue(),
                map.get("reasoningTokens") == null ? null : ((Number) map.get("reasoningTokens")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
