package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The provider-neutral response produced by the model gateway (ADR-0010 §1). Usage and cost
 * recorded here are the gateway's own measurements and are authoritative: ADR-0004 §9 forbids
 * taking them from the agent runtime's summary.
 *
 * Generated by .github/scripts/codegen.py from schemas/model/model-response.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ModelResponse(
        @Required String protocolVersion,
        @Required String modelInvocationId,
        @Required ModelResponseFinishReason finishReason,
        @Required ModelResponseUsage usage,
        @Required String providerModelId,
        @Required long latencyMs,
        List<ModelResponseContentItem> content,
        List<ModelResponseToolCallsItem> toolCalls,
        ModelResponseCost cost,
        ModelResponseError error
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("protocolVersion", protocolVersion);
        map.put("modelInvocationId", modelInvocationId);
        map.put("finishReason", finishReason.wire());
        map.put("usage", usage.toMap());
        map.put("providerModelId", providerModelId);
        map.put("latencyMs", latencyMs);
        if (content != null) {
            map.put("content", content.stream().map(ModelResponseContentItem::toMap).toList());
        }
        if (toolCalls != null) {
            map.put("toolCalls", toolCalls.stream().map(ModelResponseToolCallsItem::toMap).toList());
        }
        if (cost != null) {
            map.put("cost", cost.toMap());
        }
        if (error != null) {
            map.put("error", error.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ModelResponse fromMap(Map<String, Object> map) {
        return new ModelResponse(
                (String) map.get("protocolVersion"),
                (String) map.get("modelInvocationId"),
                ModelResponseFinishReason.fromWire((String) map.get("finishReason")),
                ModelResponseUsage.fromMap(asMap(map.get("usage"))),
                (String) map.get("providerModelId"),
                ((Number) map.get("latencyMs")).longValue(),
                map.get("content") == null ? null : asList(map.get("content")).stream().map(e -> ModelResponseContentItem.fromMap(asMap(e))).toList(),
                map.get("toolCalls") == null ? null : asList(map.get("toolCalls")).stream().map(e -> ModelResponseToolCallsItem.fromMap(asMap(e))).toList(),
                map.get("cost") == null ? null : ModelResponseCost.fromMap(asMap(map.get("cost"))),
                map.get("error") == null ? null : ModelResponseError.fromMap(asMap(map.get("error")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
