package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/model/model-request.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ModelRequestBudgets(
        @Required long maxInputTokens,
        @Required long maxOutputTokens,
        @Required long timeoutMs
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("maxInputTokens", maxInputTokens);
        map.put("maxOutputTokens", maxOutputTokens);
        map.put("timeoutMs", timeoutMs);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ModelRequestBudgets fromMap(Map<String, Object> map) {
        return new ModelRequestBudgets(
                ((Number) map.get("maxInputTokens")).longValue(),
                ((Number) map.get("maxOutputTokens")).longValue(),
                ((Number) map.get("timeoutMs")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
