package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/model/model-request.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ModelRequestMessagesItemRole {
    USER("USER"),
    ASSISTANT("ASSISTANT"),
    TOOL_RESULT("TOOL_RESULT");

    private final String wire;

    ModelRequestMessagesItemRole(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ModelRequestMessagesItemRole fromWire(String value) {
        for (ModelRequestMessagesItemRole candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ModelRequestMessagesItemRole value: " + value);
    }
}
