package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/model/model-response.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ModelResponseError(
        @Required ModelResponseErrorCategory category,
        @Required String message,
        Long retryAfterMs
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("category", category.wire());
        map.put("message", message);
        if (retryAfterMs != null) {
            map.put("retryAfterMs", retryAfterMs);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ModelResponseError fromMap(Map<String, Object> map) {
        return new ModelResponseError(
                ModelResponseErrorCategory.fromWire((String) map.get("category")),
                (String) map.get("message"),
                map.get("retryAfterMs") == null ? null : ((Number) map.get("retryAfterMs")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
