package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/model/model-request.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ModelRequestParams(
        Double temperature,
        Double topP,
        Long maxOutputTokens,
        List<String> stopSequences
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (temperature != null) {
            map.put("temperature", temperature);
        }
        if (topP != null) {
            map.put("topP", topP);
        }
        if (maxOutputTokens != null) {
            map.put("maxOutputTokens", maxOutputTokens);
        }
        if (stopSequences != null) {
            map.put("stopSequences", stopSequences);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ModelRequestParams fromMap(Map<String, Object> map) {
        return new ModelRequestParams(
                map.get("temperature") == null ? null : ((Number) map.get("temperature")).doubleValue(),
                map.get("topP") == null ? null : ((Number) map.get("topP")).doubleValue(),
                map.get("maxOutputTokens") == null ? null : ((Number) map.get("maxOutputTokens")).longValue(),
                map.get("stopSequences") == null ? null : asList(map.get("stopSequences"))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
