package io.aiplatform.contracts;

/**
 * Discriminates the branches of the union. The members are the union of the values each branch
 * permits.
 *
 * Generated by .github/scripts/codegen.py from schemas/common/common.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum NetworkPolicyMode {
    NONE("NONE"),
    ALLOWLIST("ALLOWLIST");

    private final String wire;

    NetworkPolicyMode(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static NetworkPolicyMode fromWire(String value) {
        for (NetworkPolicyMode candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown NetworkPolicyMode value: " + value);
    }
}
