package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * ADR-0003 §3: mandatory on every execution request, so connectivity is a decision rather than
 * a default. Union of mutually exclusive branches; exactly one branch's required fields are
 * present in a valid document, which the JSON Schema enforces and this type does not.
 *
 * Generated by .github/scripts/codegen.py from schemas/common/common.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record NetworkPolicy(
        NetworkPolicyMode mode,
        List<String> hosts
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (mode != null) {
            map.put("mode", mode.wire());
        }
        if (hosts != null) {
            map.put("hosts", hosts);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static NetworkPolicy fromMap(Map<String, Object> map) {
        return new NetworkPolicy(
                map.get("mode") == null ? null : NetworkPolicyMode.fromWire((String) map.get("mode")),
                map.get("hosts") == null ? null : asList(map.get("hosts"))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
