package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The durable record of one node attempt (ADR-0008 §7). Identity is the four-part key (runId,
 * nodeId, iteration, attempt) fixed by ADR-0021 §1. Records are never overwritten by a retry:
 * each attempt keeps its own record, because evaluation depends on being able to see how
 * failures evolved.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/node-run.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record NodeRun(
        @Required String schemaVersion,
        @Required String runId,
        @Required String nodeId,
        @Required long iteration,
        @Required long attempt,
        @Required long version,
        @Required NodeRunNodeType nodeType,
        @Required NodeRunStatus status,
        String capabilityGrantId,
        String contextBundleRef,
        Map<String, Object> claimedOutput,
        Map<String, Object> validatedOutput,
        Boolean outputValid,
        NodeRunStopReason stopReason,
        GraphRunFailure failure,
        String nextAttemptAt,
        FailureCategory lastFailureCategory,
        NodeRunIndeterminateReason indeterminateReason,
        String deadline,
        String startedAt,
        String endedAt
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("runId", runId);
        map.put("nodeId", nodeId);
        map.put("iteration", iteration);
        map.put("attempt", attempt);
        map.put("version", version);
        map.put("nodeType", nodeType.wire());
        map.put("status", status.wire());
        if (capabilityGrantId != null) {
            map.put("capabilityGrantId", capabilityGrantId);
        }
        if (contextBundleRef != null) {
            map.put("contextBundleRef", contextBundleRef);
        }
        if (claimedOutput != null) {
            map.put("claimedOutput", claimedOutput);
        }
        if (validatedOutput != null) {
            map.put("validatedOutput", validatedOutput);
        }
        if (outputValid != null) {
            map.put("outputValid", outputValid);
        }
        if (stopReason != null) {
            map.put("stopReason", stopReason.wire());
        }
        if (failure != null) {
            map.put("failure", failure.toMap());
        }
        if (nextAttemptAt != null) {
            map.put("nextAttemptAt", nextAttemptAt);
        }
        if (lastFailureCategory != null) {
            map.put("lastFailureCategory", lastFailureCategory.wire());
        }
        if (indeterminateReason != null) {
            map.put("indeterminateReason", indeterminateReason.toMap());
        }
        if (deadline != null) {
            map.put("deadline", deadline);
        }
        if (startedAt != null) {
            map.put("startedAt", startedAt);
        }
        if (endedAt != null) {
            map.put("endedAt", endedAt);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static NodeRun fromMap(Map<String, Object> map) {
        return new NodeRun(
                (String) map.get("schemaVersion"),
                (String) map.get("runId"),
                (String) map.get("nodeId"),
                ((Number) map.get("iteration")).longValue(),
                ((Number) map.get("attempt")).longValue(),
                ((Number) map.get("version")).longValue(),
                NodeRunNodeType.fromWire((String) map.get("nodeType")),
                NodeRunStatus.fromWire((String) map.get("status")),
                map.get("capabilityGrantId") == null ? null : (String) map.get("capabilityGrantId"),
                map.get("contextBundleRef") == null ? null : (String) map.get("contextBundleRef"),
                map.get("claimedOutput") == null ? null : (Map<String, Object>) map.get("claimedOutput"),
                map.get("validatedOutput") == null ? null : (Map<String, Object>) map.get("validatedOutput"),
                map.get("outputValid") == null ? null : (Boolean) map.get("outputValid"),
                map.get("stopReason") == null ? null : NodeRunStopReason.fromWire((String) map.get("stopReason")),
                map.get("failure") == null ? null : GraphRunFailure.fromMap(asMap(map.get("failure"))),
                map.get("nextAttemptAt") == null ? null : (String) map.get("nextAttemptAt"),
                map.get("lastFailureCategory") == null ? null : FailureCategory.fromWire((String) map.get("lastFailureCategory")),
                map.get("indeterminateReason") == null ? null : NodeRunIndeterminateReason.fromMap(asMap(map.get("indeterminateReason"))),
                map.get("deadline") == null ? null : (String) map.get("deadline"),
                map.get("startedAt") == null ? null : (String) map.get("startedAt"),
                map.get("endedAt") == null ? null : (String) map.get("endedAt")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
