package io.aiplatform.contracts;

/**
 * ADR-0008 §7. INDETERMINATE is entered when a write-ahead intent record exists with no
 * matching outcome: a side effect may or may not have occurred. Most workflow engines omit
 * this state and then discover they need it after posting two pull requests for the same
 * issue.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/node-run.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum NodeRunStatus {
    PENDING("PENDING"),
    SCHEDULED("SCHEDULED"),
    RUNNING("RUNNING"),
    SUCCEEDED("SUCCEEDED"),
    AWAITING_APPROVAL("AWAITING_APPROVAL"),
    AWAITING_RETRY("AWAITING_RETRY"),
    FAILED("FAILED"),
    SKIPPED("SKIPPED"),
    CANCELLED("CANCELLED"),
    INDETERMINATE("INDETERMINATE");

    private final String wire;

    NodeRunStatus(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static NodeRunStatus fromWire(String value) {
        for (NodeRunStatus candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown NodeRunStatus value: " + value);
    }
}
