package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Populated only when status is INDETERMINATE. ADR-0008 Security Impact: this must be visible
 * to an operator. A silently swallowed indeterminate side effect is worse than a loud failure.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/node-run.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record NodeRunIndeterminateReason(
        @Required String toolId,
        @Required String idempotencyKey,
        @Required String intentRecordedAt,
        String reconciliationHint
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("toolId", toolId);
        map.put("idempotencyKey", idempotencyKey);
        map.put("intentRecordedAt", intentRecordedAt);
        if (reconciliationHint != null) {
            map.put("reconciliationHint", reconciliationHint);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static NodeRunIndeterminateReason fromMap(Map<String, Object> map) {
        return new NodeRunIndeterminateReason(
                (String) map.get("toolId"),
                (String) map.get("idempotencyKey"),
                (String) map.get("intentRecordedAt"),
                map.get("reconciliationHint") == null ? null : (String) map.get("reconciliationHint")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
