package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/graph/node-run.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum NodeRunNodeType {
    CONTEXT("context"),
    AGENT("agent"),
    TOOL("tool"),
    APPROVAL("approval"),
    DECISION("decision"),
    LOOP("loop"),
    TERMINAL("terminal");

    private final String wire;

    NodeRunNodeType(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static NodeRunNodeType fromWire(String value) {
        for (NodeRunNodeType candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown NodeRunNodeType value: " + value);
    }
}
