package io.aiplatform.contracts;

/**
 * Why a loop node stopped iterating (ADR-0021 §4). Recording which bound fired is what makes
 * 'the loop burned the budget' diagnosable without reading logs. Present only on loop nodes;
 * the iteration count is derivable from the NodeRun records and is deliberately not
 * denormalised here, where it could disagree with them.
 *
 * Generated by .github/scripts/codegen.py from schemas/graph/node-run.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum NodeRunStopReason {
    EXIT_CONDITION_MET("EXIT_CONDITION_MET"),
    MAX_ITERATIONS("MAX_ITERATIONS"),
    BODY_FAILED("BODY_FAILED"),
    BUDGET_EXCEEDED("BUDGET_EXCEEDED"),
    CANCELLED("CANCELLED"),
    DEADLINE_EXCEEDED("DEADLINE_EXCEEDED");

    private final String wire;

    NodeRunStopReason(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static NodeRunStopReason fromWire(String value) {
        for (NodeRunStopReason candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown NodeRunStopReason value: " + value);
    }
}
