package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Allow/deny globs for one repository. Globs are repository-relative: 'src/**' inside this
 * entry can only ever mean that path inside the repository the entry is keyed by. Glob
 * semantics are restricted (ADR-0023 §4): '*' matches within one segment, '**' matches whole
 * segments, and there is no brace expansion or regular-expression syntax.
 *
 * Generated by .github/scripts/codegen.py from schemas/common/common.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record PathScopeEntry(
        List<String> allow,
        List<String> deny
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (allow != null) {
            map.put("allow", allow);
        }
        if (deny != null) {
            map.put("deny", deny);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static PathScopeEntry fromMap(Map<String, Object> map) {
        return new PathScopeEntry(
                map.get("allow") == null ? null : asList(map.get("allow")),
                map.get("deny") == null ? null : asList(map.get("deny"))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
