package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/registry/repository-record.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum RepositoryRecordStatus {
    ACTIVE("ACTIVE"),
    SUSPENDED("SUSPENDED");

    private final String wire;

    RepositoryRecordStatus(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static RepositoryRecordStatus fromWire(String value) {
        for (RepositoryRecordStatus candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown RepositoryRecordStatus value: " + value);
    }
}
