package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Identifies what to materialise into a workspace. With baseSha and the patch series this
 * reconstructs a workspace (ADR-0003 §6).
 *
 * Generated by .github/scripts/codegen.py from schemas/common/common.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record RepoRef(
        @Required String repositoryId,
        @Required String remote,
        @Required String ref,
        String commitSha
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("repositoryId", repositoryId);
        map.put("remote", remote);
        map.put("ref", ref);
        if (commitSha != null) {
            map.put("commitSha", commitSha);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static RepoRef fromMap(Map<String, Object> map) {
        return new RepoRef(
                (String) map.get("repositoryId"),
                (String) map.get("remote"),
                (String) map.get("ref"),
                map.get("commitSha") == null ? null : (String) map.get("commitSha")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
