package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A repository the platform is allowed to work in (ADR-0014). The record is the capability
 * ceiling for that repository. ADR-0014 §5 fixes the precedence: platform policy, then
 * trust-level ceiling, then this record, then the graph node definition — each layer may only
 * narrow. Files resident in the target repository affect context only and have zero capability
 * effect, which is what stops a repository the platform is editing from rewriting the
 * configuration that governs editing it.
 *
 * Generated by .github/scripts/codegen.py from schemas/registry/repository-record.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record RepositoryRecord(
        @Required String schemaVersion,
        @Required String repositoryId,
        @Required String displayName,
        @Required List<String> remotes,
        @Required String defaultBranch,
        @Required TrustLevel trustLevel,
        @Required String toolImage,
        @Required List<CommandProfile> commandProfiles,
        @Required RepositoryRecordCapabilityCeiling capabilityCeiling,
        @Required RepositoryRecordContextPolicy contextPolicy,
        @Required RepositoryRecordVerification verification,
        @Required List<String> owners,
        @Required RepositoryRecordStatus status,
        @Required String registeredBy,
        @Required String registeredAt,
        @Required String configHash
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("repositoryId", repositoryId);
        map.put("displayName", displayName);
        map.put("remotes", remotes);
        map.put("defaultBranch", defaultBranch);
        map.put("trustLevel", trustLevel.wire());
        map.put("toolImage", toolImage);
        map.put("commandProfiles", commandProfiles.stream().map(CommandProfile::toMap).toList());
        map.put("capabilityCeiling", capabilityCeiling.toMap());
        map.put("contextPolicy", contextPolicy.toMap());
        map.put("verification", verification.toMap());
        map.put("owners", owners);
        map.put("status", status.wire());
        map.put("registeredBy", registeredBy);
        map.put("registeredAt", registeredAt);
        map.put("configHash", configHash);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static RepositoryRecord fromMap(Map<String, Object> map) {
        return new RepositoryRecord(
                (String) map.get("schemaVersion"),
                (String) map.get("repositoryId"),
                (String) map.get("displayName"),
                asList(map.get("remotes")),
                (String) map.get("defaultBranch"),
                TrustLevel.fromWire((String) map.get("trustLevel")),
                (String) map.get("toolImage"),
                asList(map.get("commandProfiles")).stream().map(e -> CommandProfile.fromMap(asMap(e))).toList(),
                RepositoryRecordCapabilityCeiling.fromMap(asMap(map.get("capabilityCeiling"))),
                RepositoryRecordContextPolicy.fromMap(asMap(map.get("contextPolicy"))),
                RepositoryRecordVerification.fromMap(asMap(map.get("verification"))),
                asList(map.get("owners")),
                RepositoryRecordStatus.fromWire((String) map.get("status")),
                (String) map.get("registeredBy"),
                (String) map.get("registeredAt"),
                (String) map.get("configHash")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
