package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/registry/repository-record.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record RepositoryRecordCapabilityCeiling(
        @Required SideEffectClass maxSideEffect,
        @Required List<String> allowedTools,
        @Required List<String> networkAllowlist,
        @Required Map<String, PathScopeEntry> pathScope,
        List<SideEffectClass> approvalOverrides,
        RepositoryRecordCapabilityCeilingBudgetCeiling budgetCeiling
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("maxSideEffect", maxSideEffect.wire());
        map.put("allowedTools", allowedTools);
        map.put("networkAllowlist", networkAllowlist);
        map.put("pathScope", pathScope.entrySet().stream().collect(java.util.stream.Collectors.toMap(java.util.Map.Entry::getKey, e -> e.getValue().toMap())));
        if (approvalOverrides != null) {
            map.put("approvalOverrides", approvalOverrides.stream().map(SideEffectClass::wire).toList());
        }
        if (budgetCeiling != null) {
            map.put("budgetCeiling", budgetCeiling.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static RepositoryRecordCapabilityCeiling fromMap(Map<String, Object> map) {
        return new RepositoryRecordCapabilityCeiling(
                SideEffectClass.fromWire((String) map.get("maxSideEffect")),
                asList(map.get("allowedTools")),
                asList(map.get("networkAllowlist")),
                asMap(map.get("pathScope")).entrySet().stream().collect(java.util.stream.Collectors.toMap(java.util.Map.Entry::getKey, e -> PathScopeEntry.fromMap(asMap(e.getValue())))),
                map.get("approvalOverrides") == null ? null : asList(map.get("approvalOverrides")).stream().map(e -> SideEffectClass.fromWire((String) e)).toList(),
                map.get("budgetCeiling") == null ? null : RepositoryRecordCapabilityCeilingBudgetCeiling.fromMap(asMap(map.get("budgetCeiling")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
