package io.aiplatform.contracts;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a record component that the source schema lists in {@code required}.
 *
 * This is metadata, not validation (ADR-0024 §4): nothing checks it at
 * construction time. It exists so that required-ness survives into the compiled
 * artifact, where the cross-language conformance check can compare it against
 * the Python models and the schema. Without it, an optional String and a
 * required String are indistinguishable by reflection, and the check would
 * silently verify nothing.
 *
 * Generated by .github/scripts/codegen.py.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.RECORD_COMPONENT, ElementType.PARAMETER})
public @interface Required {
}
