package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/common/common.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ResourceUsage(
        Long cpuMillis,
        Long maxMemoryBytes,
        Long diskBytesWritten
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (cpuMillis != null) {
            map.put("cpuMillis", cpuMillis);
        }
        if (maxMemoryBytes != null) {
            map.put("maxMemoryBytes", maxMemoryBytes);
        }
        if (diskBytesWritten != null) {
            map.put("diskBytesWritten", diskBytesWritten);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ResourceUsage fromMap(Map<String, Object> map) {
        return new ResourceUsage(
                map.get("cpuMillis") == null ? null : ((Number) map.get("cpuMillis")).longValue(),
                map.get("maxMemoryBytes") == null ? null : ((Number) map.get("maxMemoryBytes")).longValue(),
                map.get("diskBytesWritten") == null ? null : ((Number) map.get("diskBytesWritten")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
