package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by .github/scripts/codegen.py from schemas/common/common.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ResourceLimits(
        @Required long cpuMillis,
        @Required long memoryBytes,
        @Required long pids,
        @Required long diskBytes
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("cpuMillis", cpuMillis);
        map.put("memoryBytes", memoryBytes);
        map.put("pids", pids);
        map.put("diskBytes", diskBytes);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ResourceLimits fromMap(Map<String, Object> map) {
        return new ResourceLimits(
                ((Number) map.get("cpuMillis")).longValue(),
                ((Number) map.get("memoryBytes")).longValue(),
                ((Number) map.get("pids")).longValue(),
                ((Number) map.get("diskBytes")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
