package io.aiplatform.contracts;

/**
 * ADR-0005 §3. Ordered from least to most consequential; a grant may narrow, never widen.
 *
 * Generated by .github/scripts/codegen.py from schemas/common/common.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum SideEffectClass {
    READ("READ"),
    WORKSPACE_WRITE("WORKSPACE_WRITE"),
    EXTERNAL_WRITE("EXTERNAL_WRITE"),
    IRREVERSIBLE("IRREVERSIBLE");

    private final String wire;

    SideEffectClass(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static SideEffectClass fromWire(String value) {
        for (SideEffectClass candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown SideEffectClass value: " + value);
    }
}
