package io.aiplatform.contracts;

/**
 * NATURAL: the external system deduplicates, or a natural key exists. KEYED: requires a
 * platform-derived idempotency key. NONE: only permissible for READ.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/tool.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ToolIdempotency {
    NATURAL("NATURAL"),
    KEYED("KEYED"),
    NONE("NONE");

    private final String wire;

    ToolIdempotency(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ToolIdempotency fromWire(String value) {
        for (ToolIdempotency candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ToolIdempotency value: " + value);
    }
}
