package io.aiplatform.contracts;

/**
 * COMPLETED: executed, output present. DENIED: authorization refused; the reason is
 * model-facing so the agent can adapt rather than retry blindly. AWAITING_APPROVAL: a human
 * decision is required and the node attempt is suspended (ADR-0009). FAILED: attempted and
 * failed. INDETERMINATE: the platform cannot establish whether the external effect occurred —
 * distinct from FAILED because a blind retry of an EXTERNAL_WRITE could duplicate it (ADR-0005
 * §3).
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/tool-result.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ToolResultStatus {
    COMPLETED("COMPLETED"),
    DENIED("DENIED"),
    AWAITING_APPROVAL("AWAITING_APPROVAL"),
    FAILED("FAILED"),
    INDETERMINATE("INDETERMINATE");

    private final String wire;

    ToolResultStatus(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ToolResultStatus fromWire(String value) {
        for (ToolResultStatus candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ToolResultStatus value: " + value);
    }
}
