package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The declared contract of a versioned tool (ADR-0005 §2). Tools are data and are immutable
 * per version. The agent runtime holds tool definitions only, never implementations, and
 * cannot invoke a tool by any path other than the control-plane choke point.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/tool.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record Tool(
        @Required String schemaVersion,
        @Required String id,
        @Required String version,
        @Required String title,
        @Required String description,
        @Required Map<String, Object> inputSchema,
        @Required Map<String, Object> outputSchema,
        @Required SideEffectClass sideEffectClass,
        @Required ToolIdempotency idempotency,
        @Required ToolApprovalPolicy approvalPolicy,
        @Required long timeoutMs,
        ToolScopeRequirements scopeRequirements,
        ToolCostHint costHint
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("id", id);
        map.put("version", version);
        map.put("title", title);
        map.put("description", description);
        map.put("inputSchema", inputSchema);
        map.put("outputSchema", outputSchema);
        map.put("sideEffectClass", sideEffectClass.wire());
        map.put("idempotency", idempotency.wire());
        map.put("approvalPolicy", approvalPolicy.toMap());
        map.put("timeoutMs", timeoutMs);
        if (scopeRequirements != null) {
            map.put("scopeRequirements", scopeRequirements.toMap());
        }
        if (costHint != null) {
            map.put("costHint", costHint.wire());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static Tool fromMap(Map<String, Object> map) {
        return new Tool(
                (String) map.get("schemaVersion"),
                (String) map.get("id"),
                (String) map.get("version"),
                (String) map.get("title"),
                (String) map.get("description"),
                (Map<String, Object>) map.get("inputSchema"),
                (Map<String, Object>) map.get("outputSchema"),
                SideEffectClass.fromWire((String) map.get("sideEffectClass")),
                ToolIdempotency.fromWire((String) map.get("idempotency")),
                ToolApprovalPolicy.fromMap(asMap(map.get("approvalPolicy"))),
                ((Number) map.get("timeoutMs")).longValue(),
                map.get("scopeRequirements") == null ? null : ToolScopeRequirements.fromMap(asMap(map.get("scopeRequirements"))),
                map.get("costHint") == null ? null : ToolCostHint.fromWire((String) map.get("costHint"))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
