package io.aiplatform.contracts;

/**
 * Generated by .github/scripts/codegen.py from schemas/tools/tool-result.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ToolResultDenialReason {
    TOOL_NOT_GRANTED("TOOL_NOT_GRANTED"),
    REPOSITORY_OUT_OF_SCOPE("REPOSITORY_OUT_OF_SCOPE"),
    PATH_OUT_OF_SCOPE("PATH_OUT_OF_SCOPE"),
    SIDE_EFFECT_EXCEEDS_CEILING("SIDE_EFFECT_EXCEEDS_CEILING"),
    INPUT_VALIDATION_FAILED("INPUT_VALIDATION_FAILED"),
    BUDGET_EXCEEDED("BUDGET_EXCEEDED"),
    GRANT_EXPIRED("GRANT_EXPIRED");

    private final String wire;

    ToolResultDenialReason(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ToolResultDenialReason fromWire(String value) {
        for (ToolResultDenialReason candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ToolResultDenialReason value: " + value);
    }
}
