package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The outcome of a ToolRequest, returned by the control-plane tool layer (ADR-0005 §4). A
 * denial, a pending approval and a failure are all results — the runtime is told what happened
 * rather than left to infer it from an error. Output is returned as data and is treated as
 * UNTRUSTED by the agent runtime: it is rendered where the model protocol expects tool output,
 * never where it expects platform instructions.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/tool-result.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ToolResult(
        @Required String protocolVersion,
        @Required String toolCallId,
        @Required ToolResultStatus status,
        @Required SideEffectClass sideEffectClass,
        @Required String completedAt,
        Map<String, Object> output,
        ArtifactRef outputRef,
        ToolResultDenial denial,
        String approvalId,
        ToolResultFailure failure,
        Long durationMs
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("protocolVersion", protocolVersion);
        map.put("toolCallId", toolCallId);
        map.put("status", status.wire());
        map.put("sideEffectClass", sideEffectClass.wire());
        map.put("completedAt", completedAt);
        if (output != null) {
            map.put("output", output);
        }
        if (outputRef != null) {
            map.put("outputRef", outputRef.toMap());
        }
        if (denial != null) {
            map.put("denial", denial.toMap());
        }
        if (approvalId != null) {
            map.put("approvalId", approvalId);
        }
        if (failure != null) {
            map.put("failure", failure.toMap());
        }
        if (durationMs != null) {
            map.put("durationMs", durationMs);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ToolResult fromMap(Map<String, Object> map) {
        return new ToolResult(
                (String) map.get("protocolVersion"),
                (String) map.get("toolCallId"),
                ToolResultStatus.fromWire((String) map.get("status")),
                SideEffectClass.fromWire((String) map.get("sideEffectClass")),
                (String) map.get("completedAt"),
                map.get("output") == null ? null : (Map<String, Object>) map.get("output"),
                map.get("outputRef") == null ? null : ArtifactRef.fromMap(asMap(map.get("outputRef"))),
                map.get("denial") == null ? null : ToolResultDenial.fromMap(asMap(map.get("denial"))),
                map.get("approvalId") == null ? null : (String) map.get("approvalId"),
                map.get("failure") == null ? null : ToolResultFailure.fromMap(asMap(map.get("failure"))),
                map.get("durationMs") == null ? null : ((Number) map.get("durationMs")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
