package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * A request to invoke a Tool, submitted by the agent runtime to the control-plane tool layer
 * (ADR-0005 §4). It is a request, not an invocation: nothing has been authorized when this
 * message is constructed, and the model's proposal and the platform's decision are
 * deliberately separate documents. Authorization, approval and execution all happen on the
 * control-plane side of this boundary, so the runtime cannot widen its own authority by asking
 * differently.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/tool-request.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ToolRequest(
        @Required String protocolVersion,
        @Required String toolCallId,
        @Required String toolId,
        @Required String toolVersion,
        @Required String callbackToken,
        @Required Map<String, Object> input,
        @Required String requestedAt,
        String idempotencyKey
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("protocolVersion", protocolVersion);
        map.put("toolCallId", toolCallId);
        map.put("toolId", toolId);
        map.put("toolVersion", toolVersion);
        map.put("callbackToken", callbackToken);
        map.put("input", input);
        map.put("requestedAt", requestedAt);
        if (idempotencyKey != null) {
            map.put("idempotencyKey", idempotencyKey);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ToolRequest fromMap(Map<String, Object> map) {
        return new ToolRequest(
                (String) map.get("protocolVersion"),
                (String) map.get("toolCallId"),
                (String) map.get("toolId"),
                (String) map.get("toolVersion"),
                (String) map.get("callbackToken"),
                (Map<String, Object>) map.get("input"),
                (String) map.get("requestedAt"),
                map.get("idempotencyKey") == null ? null : (String) map.get("idempotencyKey")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
