package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Present when status is DENIED. The reason is deliberately model-facing and specific enough
 * to be actionable, but never discloses what the grant would have permitted — that would turn
 * a denial into an enumeration oracle for the agent's own boundary.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/tool-result.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ToolResultDenial(
        @Required ToolResultDenialReason reason,
        @Required String message
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("reason", reason.wire());
        map.put("message", message);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ToolResultDenial fromMap(Map<String, Object> map) {
        return new ToolResultDenial(
                ToolResultDenialReason.fromWire((String) map.get("reason")),
                (String) map.get("message")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
