package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Which scopes a grant must contain for this tool to be invocable.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/tool.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ToolScopeRequirements(
        Boolean repository,
        Boolean path,
        Boolean externalProject
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (repository != null) {
            map.put("repository", repository);
        }
        if (path != null) {
            map.put("path", path);
        }
        if (externalProject != null) {
            map.put("externalProject", externalProject);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ToolScopeRequirements fromMap(Map<String, Object> map) {
        return new ToolScopeRequirements(
                map.get("repository") == null ? null : (Boolean) map.get("repository"),
                map.get("path") == null ? null : (Boolean) map.get("path"),
                map.get("externalProject") == null ? null : (Boolean) map.get("externalProject")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
