package io.aiplatform.contracts;

/**
 * Discriminates the branches of the union. The members are the union of the values each branch
 * permits.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/tool.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum ToolApprovalPolicyMode {
    NEVER("NEVER"),
    ALWAYS("ALWAYS"),
    CONDITIONAL("CONDITIONAL");

    private final String wire;

    ToolApprovalPolicyMode(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static ToolApprovalPolicyMode fromWire(String value) {
        for (ToolApprovalPolicyMode candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown ToolApprovalPolicyMode value: " + value);
    }
}
