package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * ADR-0005 §2. IRREVERSIBLE tools always require approval regardless of this field; policy may
 * strengthen the requirement but never weaken it. Union of mutually exclusive branches;
 * exactly one branch's required fields are present in a valid document, which the JSON Schema
 * enforces and this type does not.
 *
 * Generated by .github/scripts/codegen.py from schemas/tools/tool.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record ToolApprovalPolicy(
        ToolApprovalPolicyMode mode,
        ConditionExpression predicate
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        if (mode != null) {
            map.put("mode", mode.wire());
        }
        if (predicate != null) {
            map.put("predicate", predicate.toMap());
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static ToolApprovalPolicy fromMap(Map<String, Object> map) {
        return new ToolApprovalPolicy(
                map.get("mode") == null ? null : ToolApprovalPolicyMode.fromWire((String) map.get("mode")),
                map.get("predicate") == null ? null : ConditionExpression.fromMap(asMap(map.get("predicate")))
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
