package io.aiplatform.contracts;

/**
 * ADR-0014 §4.
 *
 * Generated by .github/scripts/codegen.py from schemas/common/common.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum TrustLevel {
    INTERNAL("INTERNAL"),
    RESTRICTED("RESTRICTED"),
    EXTERNAL("EXTERNAL");

    private final String wire;

    TrustLevel(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static TrustLevel fromWire(String value) {
        for (TrustLevel candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown TrustLevel value: " + value);
    }
}
