package io.aiplatform.contracts;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Records the JSON field name when it cannot be used as a Java identifier.
 *
 * Condition's {@code const} branch and CommandProfile's {@code default} parameter
 * are the cases that occur: both are Java keywords, so the generated components are
 * named {@code constValue} and {@code defaultValue}. The mapping is stated here
 * rather than inferred from a suffix convention, so that a field legitimately named
 * {@code somethingValue} is never mistaken for a renamed one.
 *
 * Generated by .github/scripts/codegen.py.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.RECORD_COMPONENT, ElementType.PARAMETER})
public @interface Wire {
    String value();
}
