package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Passed to createWorkspace() (ADR-0003 §1). One workspace per run, not per node (ADR-0003
 * §7), held under an exclusive lease so two runs never share a checkout.
 *
 * Generated by .github/scripts/codegen.py from schemas/execution/workspace-spec.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record WorkspaceSpec(
        @Required String protocolVersion,
        @Required String runId,
        @Required List<RepoRef> repositories,
        @Required String toolImage,
        @Required ResourceLimits resourceLimits,
        @Required long leaseTtlMs
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("protocolVersion", protocolVersion);
        map.put("runId", runId);
        map.put("repositories", repositories.stream().map(RepoRef::toMap).toList());
        map.put("toolImage", toolImage);
        map.put("resourceLimits", resourceLimits.toMap());
        map.put("leaseTtlMs", leaseTtlMs);
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static WorkspaceSpec fromMap(Map<String, Object> map) {
        return new WorkspaceSpec(
                (String) map.get("protocolVersion"),
                (String) map.get("runId"),
                asList(map.get("repositories")).stream().map(e -> RepoRef.fromMap(asMap(e))).toList(),
                (String) map.get("toolImage"),
                ResourceLimits.fromMap(asMap(map.get("resourceLimits"))),
                ((Number) map.get("leaseTtlMs")).longValue()
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
