package io.aiplatform.contracts;

/**
 * container is the default and the only mode with the isolation guarantees of ADR-0006 §4.
 * unsafe-host-exec is an escape hatch that is disabled by default, requires a configuration
 * change rather than a run flag, and is recorded here and on every audit entry so evaluation
 * results produced under it can be excluded from comparison.
 *
 * Generated by .github/scripts/codegen.py from schemas/execution/workspace.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum WorkspaceExecutionMode {
    CONTAINER("container"),
    UNSAFE_HOST_EXEC("unsafe-host-exec");

    private final String wire;

    WorkspaceExecutionMode(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static WorkspaceExecutionMode fromWire(String value) {
        for (WorkspaceExecutionMode candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown WorkspaceExecutionMode value: " + value);
    }
}
