package io.aiplatform.contracts;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The durable record of an isolated, reconstructible, credential-free materialisation of one
 * or more repositories for exactly one GraphRun (ADR-0003 §7, ADR-0006). WorkspaceSpec is the
 * creation input; this is the record. The record exists because a workspace outlives the
 * process that created it: after a crash the platform must be able to tell whether a workspace
 * is still leased, reclaimable or quarantined, and losing that knowledge means either leaking
 * disk or destroying a workspace another process is using. Layout is fixed by ADR-0023 §1: one
 * directory per repositoryId directly beneath the root.
 *
 * Generated by .github/scripts/codegen.py from schemas/execution/workspace.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public record Workspace(
        @Required String schemaVersion,
        @Required String workspaceId,
        @Required String runId,
        @Required WorkspaceStatus status,
        @Required String toolImageDigest,
        @Required List<RepoRef> repositories,
        @Required WorkspaceExecutionMode executionMode,
        @Required long quotaBytes,
        @Required String createdAt,
        WorkspaceLease lease,
        String lastUsedAt,
        String destroyedAt
) {

    /**
     * Convert to a JSON-compatible map. Absent optional fields are omitted rather
     * than written as null (ADR-0020 §3).
     */
    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("schemaVersion", schemaVersion);
        map.put("workspaceId", workspaceId);
        map.put("runId", runId);
        map.put("status", status.wire());
        map.put("toolImageDigest", toolImageDigest);
        map.put("repositories", repositories.stream().map(RepoRef::toMap).toList());
        map.put("executionMode", executionMode.wire());
        map.put("quotaBytes", quotaBytes);
        map.put("createdAt", createdAt);
        if (lease != null) {
            map.put("lease", lease.toMap());
        }
        if (lastUsedAt != null) {
            map.put("lastUsedAt", lastUsedAt);
        }
        if (destroyedAt != null) {
            map.put("destroyedAt", destroyedAt);
        }
        return map;
    }

    /** Parse from a JSON-compatible map. Performs no validation (ADR-0024 §4). */
    public static Workspace fromMap(Map<String, Object> map) {
        return new Workspace(
                (String) map.get("schemaVersion"),
                (String) map.get("workspaceId"),
                (String) map.get("runId"),
                WorkspaceStatus.fromWire((String) map.get("status")),
                (String) map.get("toolImageDigest"),
                asList(map.get("repositories")).stream().map(e -> RepoRef.fromMap(asMap(e))).toList(),
                WorkspaceExecutionMode.fromWire((String) map.get("executionMode")),
                ((Number) map.get("quotaBytes")).longValue(),
                (String) map.get("createdAt"),
                map.get("lease") == null ? null : WorkspaceLease.fromMap(asMap(map.get("lease"))),
                map.get("lastUsedAt") == null ? null : (String) map.get("lastUsedAt"),
                map.get("destroyedAt") == null ? null : (String) map.get("destroyedAt")
        );
    }

    @SuppressWarnings("unchecked")
    private static <V> Map<String, V> asMap(Object value) {
        return (Map<String, V>) value;
    }

    @SuppressWarnings("unchecked")
    private static <T> List<T> asList(Object value) {
        return (List<T>) value;
    }
}
