package io.aiplatform.contracts;

/**
 * CREATING -> READY -> LEASED, then RELEASED -> DESTROYED on success, QUARANTINED -> DESTROYED
 * on a failed run with bounded retention, or EXPIRED when the lease is lost and the workspace
 * becomes reclaimable. QUARANTINED is a distinct state rather than delayed destruction because
 * a workspace kept for diagnosis must not be handed to another run.
 *
 * Generated by .github/scripts/codegen.py from schemas/execution/workspace.schema.json.
 *
 * DO NOT EDIT. Changes belong in the schema; this file is regenerated and CI
 * fails if the committed output differs (ADR-0024 §3).
 */
public enum WorkspaceStatus {
    CREATING("CREATING"),
    READY("READY"),
    LEASED("LEASED"),
    RELEASED("RELEASED"),
    EXPIRED("EXPIRED"),
    QUARANTINED("QUARANTINED"),
    DESTROYED("DESTROYED");

    private final String wire;

    WorkspaceStatus(String wire) {
        this.wire = wire;
    }

    /** The value as it appears in JSON, which is not always the constant name. */
    public String wire() {
        return wire;
    }

    public static WorkspaceStatus fromWire(String value) {
        for (WorkspaceStatus candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException(
                "unknown WorkspaceStatus value: " + value);
    }
}
